### ISSUE TITLE
Add app-level tests

### ISSUE THREAD

**Issue by aturon** [http-rs/tide#15]
Right now the only tests are for the generic `UrlTable` type, not for `App` itself. Figure out a test harness strategy for `App` and write some tests.

**Comment by skade** [comment]
I have a sketch here: https://github.com/skade/tide/blob/testable-app/src/app.rs#L216-L251. I'll see that I can turn it into a full pull request tomorrow. (It currently doesn't report test failures correctly)

**Comment by skade** [comment]
I've been playing around with this a little more and would love to take that topic on.

**Comment by tirr-c** [comment]
@gruberb I've written a simple test backend on PR #140. Basically the backend consumes a `HttpService` and provide some interface to simulate requests synchronously. It works as a test client for our app. Once we run `TestBackend::simulate`, we can make assertions on the returned response.

Once the PR lands, we can add more integration tests to test whether `App` works as expected. Moving the test backend into a module (or even a crate) would be the good point to start. Adding helper functions like checking status codes will be helpful. Then you can easily test on some sample app structures.

**Comment by gruberb** [comment]
@tirr-c Thanks, I will have a look on your PR. So I will work on getting the test backend into a module/crate and then run tests against the app. Will get back to you once I started. I surely will need some guidance here and there! Thanks for assisting!

**Comment by yoshuawuyts** [comment]
We already run 40 or so tests for app; more would be great, but this should be good to close. Thanks!
