### ISSUE TITLE
Nested `App`s

### ISSUE THREAD

**Issue by aturon** [http-rs/tide#160]
As of #156 there is no way to "mount" an `App` within another app. We'll eventually want to work out the story here, including what happens to middleware when nesting.

**Comment by tirr-c** [comment]
We also need to think about how to perform URL reverse lookup within nested `App`s. If we nest `App`s as endpoints, it might be tough to lookup.

**Comment by PeteJodo** [comment]
nesting tide is now possible via `.nest()`, closing
