### ISSUE TITLE
Add code examples to API docs

### ISSUE THREAD

**Issue by aturon** [http-rs/tide#17]
The existing API docs were written quickly and don't have examples yet. Let's get some added!

**Comment by pbvie** [comment]
I'd like to take on this one. Seems like a great way to get to know the project.

**Comment by zacck** [comment]
How come this is open, do we need more code examples?

**Comment by yoshuawuyts** [comment]
@zacck that was the idea. But we already have quite a few docs, so there's not too much use in keeping this open. Perhaps we should do a docs push at some point though, but we can open a new issue for that.
