### ISSUE TITLE
Drop Send + Sync from ResultExt imp for std::error::Error

### ISSUE THREAD

**Issue by ghost** [http-rs/tide#184]
I'm using tera and it has an error type which is !Send, !Sync.
Is it possible to drop the these requirements in the  implementation of ResultExt for T: std::error:Error?

Note, Tera also has a related issue: Errors are not sync: https://github.com/Keats/tera/issues/381.
It'd be great if the two create were compatible by the error handling, and a simple client_err/server_err were enough without the need for an error mapping function

**Comment by yoshuawuyts** [comment]
@zpgaal those constraints can't really be loosened as Tide is an async system where we _do_ need to be able to send errors between threads, and we also have to be generic over any kind of user error. There's not much we can do about those requirements, which means we can't really change our trait requirements either.

It feels like this might be solvable as part of the repository you've linked, perhaps they might be able to help there!
