### ISSUE TITLE
How to add clone-able but `!Sync` App state?

### ISSUE THREAD

**Issue by updogliu** [http-rs/tide#196]
## Context
I was trying to add a [std::sync::mpsc::Sender](https://doc.rust-lang.org/beta/std/sync/mpsc/struct.Sender.html) to my `AppData`. My design is that the receiver would process the received data one by one and send each result back using an `futures::channel::oneshot` associated with the data. The endpoint would `await!()` on the async oneshot channel for the result. 

 Because it is `!Sync`, I have to add a `Mutex` wrapper for the `Sender`. However, if I understand it correctly, a more native way to use `Sender` is to give each user a clone of it, so that multiple users can send data concurrently.

## Question

Is it possible to add clone-able but `!Sync`  App state without resorting to `Mutex` and locking? 
If it is impossible for now, but the motivation is valid, any ideas on adding a feature for it?

**Comment by secretfader** [comment]
I have a hunch this will end up at the same answer as #184, but in the chance I misunderstood your request, could you elaborate a bit more?

If you're stuck on using channels in Tide middleware, you might take a look at @tomhoule's implementation of a cookie session middleware](https://github.com/tomhoule/tide-cookie-session/blob/master/src/lib.rs) which uses `futures::channel` to pass data.

**Comment by updogliu** [comment]
What I am asking is different to #184. I am not asking about remove the bound of `Sync`. Currently the `AppData` is shared by reference among threads, so it has to be `Sync`. What I am asking is that - is it possible to allow sharing App state by cloned values, rather than by reference. For example, we could add a `AppCloneableData` besides `AppData`, and the `Context` struct would become

```
pub struct Context<AppData> {
    app_data: Arc<AppData>,
    app_cloneable_data: AppCloneableData,
}
```
This is more of feature request actually.

In the [cookie session middleware](https://github.com/tomhoule/tide-cookie-session/blob/master/src/lib.rs) example, the sender is not shared among multiple middlewares or endpoints. Thanks anyway.

**Comment by yoshuawuyts** [comment]
A different solution to passing channels would be to use [`crossbeam`'s channel implementation](https://docs.rs/crossbeam/0.7.1/crossbeam/channel/fn.bounded.html). This _does_ implement `Send + Sync` which evades a lot of the problems here.

I feel that std channels are a bit finicky in general, and people have been talking for a while now what the best way to soft-deprecate / replace them are. In particular with the eye on bringing Crossbeam's model to std instead.

Hope this is helpful!

**Comment by updogliu** [comment]
@yoshuawuyts This is very helpful! Thank you for introducing `crossbeam::channel`. It should resolve my original problem!

However, I will left this issue open for now. I think it is worth a discussion in general.
