### ISSUE TITLE
Flesh out the README

### ISSUE THREAD

**Issue by aturon** [http-rs/tide#21]
The README should provide, at least:

- A hello-world-style example
- A quick introduction to the main concepts of Tide
- Links for where to find more information

**Comment by bIgBV** [comment]
Regarding this point:

> Links for where to find more information

For now this should be the links to the following few posts right:

* [Routing and extraction](https://rust-lang-nursery.github.io/wg-net/2018/10/16/tide-routing.html)
* [Rising tide](https://rust-lang-nursery.github.io/wg-net/2018/09/11/tide.html)
* [Middleware in Tide](https://rust-lang-nursery.github.io/wg-net/2018/11/07/tide-middleware.html)

**Comment by pickfire** [comment]
Would https://github.com/rust-net-web/tide/blob/master/examples/hello.rs be a nice example? If yes, then we could just show it with some commands below to get people started.
```
$ cargo new hello
$ echo nightly > rust-toolchain
$ echo 'tide = { git = "https://github.com/rust-net-web/tide" }' >> Cargo.toml
$ cargo run
$ curl 127.0.0.1:8000  # on another terminal
```
Is that good for a pull request as of a simple way to get beginners started? Or maybe it might be good to mention **HERE BE DRAGONS!**

**Comment by PeteJodo** [comment]
`README` could be further improved upon but it at least already covers what was laid out in this issue and is on `v0.7` while this issue was tracking for `v0.1`. Closing.
