### ISSUE TITLE
impl error combinators for Future<Result<T, E>>

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/tide#236]
With `await` syntax coming in the near future, it's worth thinking of how we'll use it. The pattern of `.await?` will likely be quite common, which is a shorthand for "await the future, and Try the result".

When using Tide's error combinators, the `.await` and `?` are split by the combinator, which makes this pattern harder to spot.

I propose we add a `FutureExt` to Tide, which extends `Future<Result<T, E>>` (or `TryFuture<T, E>`, and allows applying combinators on the Future directly, so we `.await?` can be used again.

This also has the upside that refactoring any function call to include one of Tide's error combinators can leave the `.await?` pattern intact, which should provide a smoother workflow.

This should pair nicely with #235 also.

## Proposed
```rust
use tide::EndpointResult;

async fn new_message(mut cx: Context<Database>) -> EndpointResult<String> {
    let msg = cx.body_json().client_err().await?;
    Ok(cx.state().insert(msg).to_string())
}
```
## Current
```rust
use tide::EndpointResult;

async fn new_message(mut cx: Context<Database>) -> EndpointResult<String> {
    let msg = cx.body_json().await.client_err()?;
    Ok(cx.state().insert(msg).to_string())
}
```

**Comment by kjvalencik** [comment]
`snafu` recently added a similar feature. https://github.com/shepmaster/snafu/pull/86

**Comment by yoshuawuyts** [comment]
We've implemented `?` support in a recent version of Tide
