### ISSUE TITLE
Get remote address / requester IP

### ISSUE THREAD

**Issue by milesgranger** [http-rs/tide#269]
## Question

Is there a way to obtain the remote IP of the incoming request?

Would have imagined something like [what actix-web does](https://docs.rs/actix-web/1.0.0-rc/actix_web/dev/struct.ConnectionInfo.html#method.remote) without going through the headers?
```rust
async fn echo_remote(mut ctx: Context<()>) -> String {
    ctx.connection_info().remote().to_owned()
}
```

**Comment by DCjanus** [comment]
Same question with me.

**Comment by yoshuawuyts** [comment]
Related issue: https://github.com/rustasync/http-service/issues/25.

@milesgranger we definitely want to add this, but it requires wrangling Hyper into allowing us to access this value, which has proven to be slightly challenging.

**Comment by yoshuawuyts** [comment]
Note from triage: we're still blocked on this by Hyper.

**Comment by ZakisM** [comment]
Any update on this?

**Comment by yoshuawuyts** [comment]
Given that we're constructing our own `TcpListener` now, we could probably find a way to pass it through to the end-user (:

Haven't fixed this yet though.

**Comment by meain** [comment]
I believe this can be closed now. There is now:

```rust
req.peer_addr()
```

https://github.com/http-rs/tide/blob/1797c0ed648dd2d28fda2e18d5432bd4eaf2150c/src/request.rs#L118

**Comment by jbr** [comment]
Not only is there Request::peer_addr, but there's also Request::remote, which includes some additional sources of that information when tide is running behind a reverse proxy:
```
    /// Get the remote address for this request.
    ///
    /// This is determined in the following priority:
    /// 1. `Forwarded` header `for` key
    /// 2. The first `X-Forwarded-For` header
    /// 3. Peer address of the transport
```
