### ISSUE TITLE
Route struct not exported?

### ISSUE THREAD

**Issue by StevenDoesStuffs** [http-rs/tide#304]
## Question
Where is the Route struct exported in master? On v0.2.0 its at tide::Route.

**Comment by secretfader** [comment]
[I don't think it is](https://github.com/rustasync/tide/blob/master/src/lib.rs#L23). I can't speak to why it was removed. However, if you can share more about your use case, I'd like to see every viewpoint represented as work to revamp the routing layer continues.

**Comment by yoshuawuyts** [comment]
`Route` is exported now!
