### ISSUE TITLE
Tide's Future Direction

### ISSUE THREAD

**Issue by dbettin** [http-rs/tide#325]
## Question

What is the status of tide?  It feels as if it might be dying.   Which, if true, is unfortunate.  It has some of the rust web framework ergonomics in addition to first-class async/await support.

## Additional context

I am willing to help in anyway possible. My company has plans to use the fx via Google Cloud Run. But, I need to understand the overall direction of the project.

**Comment by yoshuawuyts** [comment]
@dbettin hi! -- thanks for reaching out. You're right that development on Tide has slowed down a bit recently, but for good reason!

We've been hard at work with building [`surf`](https://docs.rs/surf/1.0.2/surf/), an HTTP client counterpart to Tide. This allowed us to experiment with some new API directions. And more recently several Tide maintainers have been working on [`async-std`](https://github.com/async-rs/async-std/), an async version of the standard library.

There's still a bit more work to do on the latter project. In particular I'm now working on building out [a complete concurrency story](https://blog.yoshuawuyts.com/futures-concurrency/), focusing on [streams](https://twitter.com/yoshuawuyts/status/1174018754428186625) next.

This shouldn't be too long anymore though. My own goal is to work for a few more weeks on `async-std`, and then take the experience we've gather building `surf` + `async-std` and pick development back up on `tide`.

It's hard for me to judge whether you should pick Tide *right now*. Things are probably going to change again soon. But I figured I'd share the full context so you get to best decide. Hope this is helpful!

**Comment by tomhoule** [comment]
I've been very short on open source time in the past months, but I want to continue participating in the near future (possibly by making https://github.com/tomhoule/tide-static-files actually usable), it would be a shame if tide didn't materialize further! I'll be on the async ecosystem discord to try to contribute to the discussion.

**Comment by yoshuawuyts** [comment]
# The road ahead

A quick update to what the plan currently is. [The rustasync working group is coming to a close](https://blog.rust-lang.org/2019/09/30/Async-await-hits-beta.html#restructuring-async-io-in-the-rust-org), which means Tide, Surf and related projects will need a new home. To that end I’ve created the [http-rs org](https://github.com/http-rs/). I’ll be moving over Tide, Surf and related crates over tomorrow.

With `async/await` stabilization around the corner (9 days!) I’d like to take the chance to ramp work back up. This includes doing a full pass over the issue tracker, updating dependencies, and making a lot of changes we’ve put off for the past few months. In particular I’d like us to get into a releasable state. This means a period of active development, but my hope is that we’ll be able to convert it into a series of actionable items from there.

Thanks everyone for having been involved with Tide & the async ecosystem WG. I’m excited for what comes next!

**Comment by dvic** [comment]
Great news! I'm looking forward to contribute to Tide! For example, a while back I encountered https://github.com/rustasync/http-service/pull/43#discussion_r333222912, that might be something I could take a stab at (depending on the first list of actionable items).

Thanks for all the hard work 👍

**Comment by secretfader** [comment]
@yoshuawuyts Sounds positive, even if the news is a bit unexpected. Can existing members of @rustasync/maintainers get access to the new org(s)?

**Comment by prasannavl** [comment]
Now `http-rs` looks awfully similar to `hyperium` org. Wondering if it's worth exploring an opportunity for a merge under the `http-rs` umbrella, if that's beneficial to the ecosystem, esp. with projects like `http`, and `h2` over there.

**Comment by yoshuawuyts** [comment]
@prasannavl I don't think merging with Hyperium is a likely option in the near future. For both technical and social reasons it's probably best if we go our separate ways for the time being.

@secretfader some maintainers have been invited to the org already. I had some trouble getting a hold of you in the past, which is why I didn't reach out about this beforehand.

In general I'd like to *really* dig into Tide for a bit, bringing it to a publishable state. This means focusing on technical work for a bit, land less so on management. We can and probably should revisit team membership in the future, but for now I'd like to punt that in favor of working on the project itself.
