### ISSUE TITLE
Set CI to Beta?

### ISSUE THREAD

**Issue by secretfader** [http-rs/tide#335]
Now that `async/await` is on beta, should we alter CI configuration to build on it instead of nightly?

**Edit:** We'd need to remove a few features that are currently in use, including `external_doc`, but I'm not sure how much milage we're getting out of those unstable features anyway.

**Comment by ar3s3ru** [comment]
Why not targeting stable directly, at this point?  
Are there other unstable features the library is using?

**Comment by yoshuawuyts** [comment]
There aren't, and we probably could (and should) target stable. The biggest feature we're waiting on is async closures though, so by the time we have that in sight we may need to enable nightly again.
