### ISSUE TITLE
redirects

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/tide#348]
I was browsing the new [warp](https://docs.rs/warp) docs, and spotted a fun module called [redirects](https://docs.rs/warp/0.1.20/warp/redirect/index.html). In it there's a small route handler to setup redirects.

I think Tide would benefit from having something similar, as doing redirects are fairly common, and having to write your own can be a bit of a hassle. Making this easy is def something we should want to do.

Importantly, we should be using [`307, temporary redirect`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) here instead of `302, permanent redirect`. This is to prevent a whole category of bugs that can come with the use of `302`.

## Example
```rust
let app = tide::new();
app.at("/hello").get(tide::redirect("/my_other_url"));
app.listen("localhost:8080").await?;
```

**Comment by lukesutton** [comment]
Have you considered allowing the redirect code to be specified, perhaps via `tide::permanent_redirect`? There are definitely cases where you want to use `302`.

**Comment by yoshuawuyts** [comment]
@lukesutton hm yeah now that you mention it perhaps we should. I like the idea you're proposing, though I'm unsure if it should be *quite* as prominent — but we should have an easy way to create a permanent redirect for sure.
