### ISSUE TITLE
Chat Link

### ISSUE THREAD

**Issue by bfrog** [http-rs/tide#355]
I'm confused by the chat link, it links to discord, so first what happened was... nothing, because I hadn't signed into the rust discord I guess.

Then it linked to a chat that had nothing in it.

Was looking to chat about tide and using it to create a matrix.org server, but where to go?

**Comment by JohnTitor** [comment]
Just notice: tide has been transferred to http-rs recently but Discord link still points to the old place on Rust Discord. So we should find a new chat space and point to there?

**Comment by paulzhang5511** [comment]
The Discord can't browse.Please use gittter.

**Comment by yoshuawuyts** [comment]
@JohnTitor yeah, we should find a new space for chat. I'm thinking perhaps we could piggy-back off the async-rs server, or else setup something new. But I don't really want to spend extra time managing more servers haha; I already have too little time haha. Do you have any opinions?

**Comment by JohnTitor** [comment]
@yoshuawuyts I don't care where it is, and I would like to provide some help if you need help :)

**Comment by yoshuawuyts** [comment]
@JohnTitor I've pinged the async-rs mods to get their input on linking to the async-rs discord server. Will wait for feedback from them before moving this ahead (:+1: 

If you haven't joined already, please feel free to! https://discord.gg/JvZeVNe

**Comment by JohnTitor** [comment]
@yoshuawuyts no worries, I've already joined!
Once the mods and admins approve that, I'm happy to submit PRs to replace the links.

**Comment by yoshuawuyts** [comment]
I believe https://discord.gg/x2gKzst should invite folks to the `tide` channel directly now; mods just approved it it seems :sparkles:
