### ISSUE TITLE
Error in README (run instead of serve)

### ISSUE THREAD

**Issue by foggy1** [http-rs/tide#356]
In b1117dd30b29193036757f320c09cd1c09e3d21b `serve` was changed to `run` all over the place. This includes in the `README` but since there isn't a new crate that method doesn't exist.

However, `serve` still exists and, in that same commit, explicitly becomes the api for `async` serving, which is the exact example in the `README`, if I'm not mistaken.

Anyway, didn't want to jump on you folks for iterating early work before releasing crates, but it does seem like in this case despite the introduction of a new function, `serve` should still be the example in the `README`.

**Comment by LukeMathWalker** [comment]
With the latest release the README now uses `listen`... So I think this issue got solved?
