### ISSUE TITLE
Add local request state/context

### ISSUE THREAD

**Issue by acasajus** [http-rs/tide#357]
Hello, 

 How could I attach a local context to a request? Ideally I would like to have a middleware that does the authentication and attaches the user object to the request so that downstream functions can get the user from the request. Is there a way to do so?

**Comment by yoshuawuyts** [comment]
@acasajus this can be done through [`Context::extensions`](https://docs.rs/tide/0.3.0/tide/struct.Context.html#method.extensions).

**Comment by acasajus** [comment]
This has been fixed in tide 0.4.0. Thanks a lot!

**Comment by balthild** [comment]
The `Context` type does not exists in tide-0.6.0 anymore. Is there any alternative approach to implement request context?

**Comment by balthild** [comment]
Sorry, I should have read the changelog. `extensions` is now provided by `Request`.
