### ISSUE TITLE
Isn't RequestLogger ready to be used?

### ISSUE THREAD

**Issue by kenkoooo** [http-rs/tide#366]
Currently, one of example middewares `RequestLogger` is disabled in v0.4.0, but I confirmed it can work on this version without any change. Is there any plan to enable it?

**Comment by yoshuawuyts** [comment]
@kenkoooo oh yeah, we should probably enable it. Perhaps out of the box even. If you'd like to file a patch it'd be most welcome!

**Comment by kenkoooo** [comment]
@yoshuawuyts Thanks! Let me work on it.
