### ISSUE TITLE
Unable to reverse proxy tide with subpath.

### ISSUE THREAD

**Issue by extraymond** [http-rs/tide#383]
Tide version: v0.5.1
OS: ubuntu linux 18.04 x64

Hi! I tried putting tide server behind a reverse proxy. For testing purposes, I tried the same with hyper.
Tried both with caddy, and here's the finding:

1. Both hyper and tide works when request with the binded url. (http://ip:port)
2. When reverse proxy with root path, both server works.
3. When proxy tide behind a supbath, for example domain/tide, tide server becomes unresponsive and returns 404 in firefox and 400 in chromium. But the hyper proxy works in the path /hyper.

Is there anything about header that needs changed manually when proxying tide behind a proxy server?

**Comment by yoshuawuyts** [comment]
@extraymond could you perhaps share more details about which paths don't work? Also if you have the time, a repro/failing test would be greatly appreciated. Thanks for the report!

**Comment by extraymond** [comment]
> @extraymond could you perhaps share more details about which paths don't work? Also if you have the time, a repro/failing test would be greatly appreciated. Thanks for the report!

Hi! I've setup a repo for debugging.
Here's the test [repo](https://github.com/extraymond/tide_reverse_proxy_test)

My platform is setup as ubuntu 18.04 x86_64, rust stable and tide v0.6.0(v0.5.1 not working as well).

Here's my investigation:
1. case1: proxy to the root path:
- sozu: works on both hyper|tide
- caddyv1: works on both
- caddyv2: works on both
2. case2: proxy under a subpath /api/:
- sozu: works only on hyper
- caddyv1: works only on hyper
- caddyv2: works only on hyper

**Comment by isgj** [comment]
@extraymond it is like so because the proxy is not striping the `/api` part from the path. Your _hyper_ server will respond to any path but  _tide_ will match exactly on `/`, since `/api` is not registered it responds with `404`.

If you change  *CaddyV1* file to:
```
localhost:5000 {
  proxy /api localhost:8080 {
    transparent
    without /api
  }
}
```

it will work also with _tide_

**Comment by extraymond** [comment]
@isgj  Thanks for your help! If I understand correctly, the deference would be hyper getting all the request and I'm only accepting request binding to prefix/ to tide.

The equivalent I should have compared would be serving the request through a middleware and compare that with hyper right? If I'm setting a middleware instead of setting up routing, the tide client is indeed working.

**Comment by isgj** [comment]
Yes exactly

**Comment by extraymond** [comment]
@isgj  Thanks for helping me out. I'm used to python's WSGI handling those stuff for me. I'll close this since it's not a bug. Thanks again.
