### ISSUE TITLE
How to build HTTPS service？

### ISSUE THREAD

**Issue by 243011068** [http-rs/tide#391]
I didn't find an example

**Comment by yoshuawuyts** [comment]
@243011068 we currently don't support HTTPS yet unfortunately.

**Comment by 243011068** [comment]
Is there any plan?

**Comment by gmosx** [comment]
You can use an `nginx` as a reverse proxy. Not a bad idea for a production setting, I guess.

**Comment by 243011068** [comment]
ok, thanks for reply
