### ISSUE TITLE
Use tide::App::new()

### ISSUE THREAD

**Issue by gmosx** [http-rs/tide#402]
Here is one minor API suggestion, for your consideration:

replace:

```rust
let mut app = tide::new();
```

with:

```rust
let mut app = tide::App::new();
```

The later seems more 'rustish' to me (the former reminds me of NodeJS, not the best of connotations). A minor change, but sometimes it's the attention to detail that matters. With this change, 'tide' is just a namespace.

(I would also prefer the name 'Service' instead of 'App', i.e. `let mut service = tide::Service::new()` but that seems more difficult to argue for ;-))

**Comment by ar3s3ru** [comment]
There's no `tide::App` defined anywhere.

Also,
```rust
let mut app = tide::new();
```
is just a shortcut for:
```rust
let mut app = tide::Server::new();
```

**Comment by gmosx** [comment]
Yeah I was suggesting to introduce `tide::App`. But actually `tide::Server` is even better ;-)
