### ISSUE TITLE
Ergonomics of `head` and `request` modules

### ISSUE THREAD

**Issue by chrisabruce** [http-rs/tide#41]
Consider merging some of the functions from `head.rs` into `request.rs` to offer a more ergonomic approach to getting parameters from a request.

Should these be moved into `request.rs` from `head.rs`:
- `pub fn uri(&self) -> &http::Uri`
- `pub fn path(&self) -> &str`
- `pub fn query(&self) -> Option<&str>`
- `pub fn method(&self) -> &http::Method`

A code example would then look more like the following:
```rust
async fn get_message(
    mut db: AppData<Database>,
    id: request::Path<usize>,
) -> Result<body::Json<Message>, StatusCode> {
    if let Some(msg) = db.get(id.0) {
        Ok(body::Json(msg))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}
```

Instead of:
```rust
async fn get_message(
    mut db: AppData<Database>,
    id: head::Path<usize>,
) -> Result<body::Json<Message>, StatusCode> {
    if let Some(msg) = db.get(id.0) {
        Ok(body::Json(msg))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}
```

**Comment by chrisabruce** [comment]
Sorry for the confusion.  To simplify, in most frameworks, you interact with a "request" type object to get data like path, method, query, etc.

So I am suggesting that maybe we figure out a way to make a call like:
`head::Path<usize>`

_look like_

`request::Path<usize>`

Maybe it is no big deal, but just considering being consistent with many other frameworks from other languages I have experienced in the past.

**Comment by aturon** [comment]
Got it, makes perfect sense!

**Comment by yoshuawuyts** [comment]
@tirr-c with https://github.com/rust-net-web/tide/pull/58 merged, is there any status update on this issue? Do you have an idea of what's left to do?

**Comment by tirr-c** [comment]
@yoshuawuyts I haven't changed anything inside `head`, but I think it's okay to merge `head` with `request`. Everything inside `head` module is about request data.

**Comment by PeteJodo** [comment]
this issue seems no longer relevant. The function signatures have changed but users do now interact with a `Request` type that is no longer tied to `http`. If I missed something here, I think opening a new issue that's geared to what tide is like today would be better
