### ISSUE TITLE
next('route') like expressjs

### ISSUE THREAD

**Issue by all789-pixel** [http-rs/tide#417]
Hello

Expressjs provide multiple callback functions that behave just like middleware, except that these callbacks can invoke ``next('route')`` to bypass the remaining route callback(s). You can use this mechanism to impose pre-conditions on a route, then pass control to subsequent routes if there is no reason to proceed with the current route. 

Example

```js
app.get('/user/:id', function (req, res, next) {
  // if the user ID is 0, skip to the next route
  if (req.params.id === '0') next('route')
  // otherwise pass the control to the next middleware function in this stack
  else next()
}, function (req, res, next) {
  // render a regular page
  res.render('regular')
})

// handler for the /user/:id path, which renders a special page
app.get('/user/:id', function (req, res, next) {
  res.render('special')
})
```

Tide can allow ``next('route')`` ?
Thank

**Comment by yoshuawuyts** [comment]
@all789-pixel We don't (or well, shouldn't) registering multiple handlers for the same route. The way to branch routes in Tide is by using conditionals *inside* route handlers:

```rust
let mut app = tide::new();
app.at("/user/:id").get(|req| async move {
    if matches!(req.param("id"), Some("0")) {
        "special"
    } else {
        "regular"
    }
});
```
Hope this is helpful!
