### ISSUE TITLE
Existing broken links

### ISSUE THREAD

**Issue by YoshiTheChinchilla** [http-rs/tide#421]
There are some broken links in README.md, because @yoshuawuyts deleted `.github` once at 063cbd880465af167e42e92dabb4098cf331768b
But I'm sorry, I don't know the reason and the context.
If it is necessary, I will revert files of `.github`.
I think it’s better than nothing.

Thanks,

### File list
- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml

### Related PR
#337

**Comment by gcapizzi** [comment]
Hey! Bumping this again, would the team be happy if we restored those files? `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` feel particularly important. Alternatively, we should at least remove the broken links from `README.md`. Thanks!

/cc @yoshuawuyts
