### ISSUE TITLE
Add tracing support

### ISSUE THREAD

**Issue by bnjjj** [http-rs/tide#425]
Hello, I'm currently thinking about adding support of tracing inside Tide. As Tide has a middleware approach it could be interesting to trace also the middlewares chain and find bottlenecks in your api for example. I started thinking about an implementation in Tide. 

Here is my proposal:

+ Add a feature flag `tracing` to enable tracing if this flag is enabled.
+ Instrument automatically middlewares and handlers with the [tracing-rs crate](https://tracing-rs.netlify.com/tracing/).

I first started to write a middleware to handle tracing in Tide but it's not possible because we have to trace all middlewares and moreover if you make a tracing middleware it becomes mandatory to execute as the last middleware to be able to trace your handlers.

Wha do you think about this proposal ? It could also be very interesting for Tide's developers to be able to know the impact of their middlewares.

I'm really open to suggestions. If you're interested let me know and I will open a draft PR to discuss about the implementation.

**Comment by bnjjj** [comment]
Ok my bad, it seems Tide already support tracing thanks to `async-log` crate. So my next steps will be to use these trace logs in order to display traces in Jaeger and see if I have enough data for my usecase.

**Comment by yoshuawuyts** [comment]
Closing as the solution here should be for `tokio-rs/tracing` to provide hooks for `log` / `async-log` to integrate.
