### ISSUE TITLE
Request::rest / *--tide-path-rest

### ISSUE THREAD

**Issue by jbr** [http-rs/tide#426]
Does tide support unnamed star routes, like `"/static/*"`? It [seems like](https://github.com/http-rs/route-recognizer/blob/master/src/lib.rs#L393-L405) route-recognizer does, and like tide [saves them in --tide-path-rest](https://github.com/http-rs/tide/blob/master/src/server/route.rs#L145-L146), but [tide::Request::rest](https://github.com/http-rs/tide/blob/master/src/request.rs#L181-L185) is only pub(crate). As far as I can tell, `--tide-path-rest` and `Request::rest` are not used anywhere in the crate. Should Request::rest be public?

**Comment by yoshuawuyts** [comment]
@jbr Thanks for asking! Yeah we support this.

**Comment by jbr** [comment]
This issue is still unresolved in that case. https://github.com/http-rs/tide/blob/master/src/request.rs#L181
