### ISSUE TITLE
Documentation: mention `features = ["attributes"]`

### ISSUE THREAD

**Issue by Walther** [http-rs/tide#431]
Thank you for creating this wonderful crate!

Being relatively new to the async/await parts of Rust, it took me a bit of head scratching to get the "Hello, World!" example in the Readme to run.

The example in the Readme:

```rust
#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    let mut app = tide::new();
    app.at("/").get(|_| async move { "Hello, world!" });
    app.listen("127.0.0.1:8080").await?;
    Ok(())
}
```

results in

```
failed to resolve: could not find `main` in `async_std`

could not find `main` in `async_std`rustc(E0433)
main.rs(1, 14): could not find `main` in `async_std`
Peek Problem (⌥F8)
No quick fixes available
```

I tried to find various possible `use` and `macro_use` statements in case something needed to be 'imported', with no success. I tried reading the Tide documentation, in case there would be some hints on how to get the example running. Finally, I started reading `async-std` docs themselves in case there would be something there.

> All examples require the "attributes" feature to be enabled. This feature is not enabled by default because it significantly impacts compile times.
> <https://docs.rs/async-std/1.5.0/async_std/#examples>

Sure enough, modifying my Cargo.toml to include `async-std = { version = "1.5.0", features = ["attributes"] }` made the code compile and I could `curl` the service locally! 🎉 🌊 

Perhaps this is something that more experienced people find obvious or easy, but for a beginner this was a tricky case of unknown unknowns.

I would be happy to submit a PR for documentation changes, if those would be desired. If so, any preferences of the form? Should the `features = ["attributes"]` be added as a comment to the Github readme code example, or as text before or after the code example, or as a new heading "requirements", something else? Where / how should this be mentioned on the Tide api docs, if any? Alternatively, if this is something that developers working with async/await "should be familiar with", feel free to close this issue.

**Comment by yoshuawuyts** [comment]
> I would be happy to submit a PR for documentation changes, if those would be desired. If so, any preferences of the form? Should the features = ["attributes"] be added as a comment to the Github readme code example, or as text before or after the code example, or as a new heading "requirements", something else? Where / how should this be mentioned on the Tide api docs, if any? Alternatively, if this is something that developers working with async/await "should be familiar with", feel free to close this issue.

Thanks for the thorough write-up @Walther! This makes sense as something that might confuse people. I'm not sure what the best way to go about it is, but perhaps adding an "Getting started" heading to both the README and lib.rs documentation could work here. The README version could probably just link to docs.rs. That way we can point people into the right direction for getting started, as I suspect you're not the first nor last person that will run into this.

Would you like to contribute this?

**Comment by prabirshrestha** [comment]
I had similar experience being new to rust. I personally would just prefer task::block_on or attribute being on by default but don’t have much experience in rust to comment on it.
