### ISSUE TITLE
h2spec tests

### ISSUE THREAD

**Issue by rustrust** [http-rs/tide#432]
For reliability and correctness tide-rs should add h2spec to testing

https://github.com/summerwind/h2spec

**Comment by yoshuawuyts** [comment]
Thanks for suggesting @rustrust. h2spec is a really cool piece of technology, but Tide probably isn't the right layer to test this at. Tide uses a pluggable backends, of which some are *only* http/1.1. As such we can't guarantee it'll pass h2spec. Instead the various backends should best tested to correctly implement the protocol, and Tide can then rely on them being correct.

Hope this makes sense!
