### ISSUE TITLE
Allow configuration of Endpoint::static_files

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/tide#447]
In https://github.com/http-rs/tide/pull/415 we've added the first version of static file support. It looks like this:

```rust
#[async_std::main]
async fn main() -> tide::Result<()> {
    let mut app = tide::new();
    app.at("/").serve_dir("/public");
    app.listen("127.0.0.1:8080").await?;
    Ok(())
}
```

Like @goto-bus-stop brought up over chat, people may want to filter files using for example predicate closures. Modifying headers can already be done through inline middleware.

The exact mechanisms for this are undecided, but a first exploration could look like this:

```rust
#[async_std::main]
async fn main() -> tide::Result<()> {
    let mut app = tide::new();
    app.at("/").serve_dir(ServeDir::new("/public").filter(|&file| true));
    app.listen("127.0.0.1:8080").await?;
    Ok(())
}
```

`ServeDir` could then have conversions from Path, String and str so that existing code using `serve_dir` continues to work if we make the bound `Endpoint::serve_dir(&mut self, impl Into<ServeDir>);`

**Comment by jbr** [comment]
If this was a try_map from the route + default fs path to an Option<fs path>, it would also allow for other transformations that might be desired, like using a different index than index.html (such as serving index.html for any file not found, as is often done for SPAs). Returning None would be whatever this filter does when it returns false, assumedly 404?

**Comment by jbr** [comment]
Before I write code for this, would using [glob](https://github.com/rust-lang-nursery/glob) meet the needs of this filter function?
That would look like:
```rust
#[async_std::main]
async fn main() -> tide::Result<()> {
    let mut app = tide::new();
    app.at("/").serve_dir("/public/**/*.jpg");
    app.listen("127.0.0.1:8080").await?;
    Ok(())
}
```
(assuming `.serve_dir("/public")` still works as "/public/*")

**Comment by yoshuawuyts** [comment]
https://github.com/http-rs/tide/issues/449 now contains an overview of `tide::fs` after a discussion yesterday on Discord.
