### ISSUE TITLE
ordering of set_header and body_string matters

### ISSUE THREAD

**Issue by prabirshrestha** [http-rs/tide#477]
This doesn't set the response header has text/html

```rust
 let res = Response::new(StatusCode::Ok)
        .set_header("content-type".parse().unwrap(), "text/html;charset=utf-8")
        .body_string("Hello<br/>".to_owned());
```

This one does set it correctly.

```rust
 let res = Response::new(StatusCode::Ok)
        .body_string("Hello<br/>".to_owned())
        .set_header("content-type".parse().unwrap(), "text/html;charset=utf-8");
```

tide = "0.8.0"

**Comment by Fishrock123** [comment]
The docs for `res.body_string` [explicitly say](https://docs.rs/tide/0.8.0/tide/struct.Response.html#method.body_string)
> The encoding is set to `text/plain; charset=utf-8`.

I do think it would probably be more developer friendly for this function to check if the `content-type` header has been set yet or not, though.

Also, if I may, recommend setting the content type through [`res.set_mime`](https://docs.rs/tide/0.8.0/tide/struct.Response.html#method.set_mime), like `tide` does internally. See https://docs.rs/mime/0.3.16/mime/index.html#constants.
```
res.set_mime(mime::TEXT_PLAIN_UTF_8)
```

**Comment by Fishrock123** [comment]
Also, it's not immediately clear but [`res.set_body(string)`](https://docs.rs/tide/0.8.0/tide/struct.Response.html#method.set_body) should also work. `res.body_string()` just does that internally.

**Comment by prabirshrestha** [comment]
Seems like `set_body` need to return `self` to make it easy to chain else need to create temp mutable vars.

**Comment by Fishrock123** [comment]
See also: https://github.com/http-rs/tide/pull/562
