### ISSUE TITLE
CONTRIBUTING.md missing

### ISSUE THREAD

**Issue by gcapizzi** [http-rs/tide#491]
Hey! 👋
I was very excited when I saw the README links to a CONTRIBUTING.md file, only to realise it's actually missing 🙁

It would be great to put it back (maybe we can dig it up from history?), but if we can't we should probably remove the link. Happy to PR either of those two things.

Thanks!

**Comment by eduardocanellas** [comment]
It looks related to #337. The issue #421 also informed about the problem. I think it's something important to restore, since the README has a Contributing section and references it.

**Comment by eduardocanellas** [comment]
@jbr I guess this one could be closed now, since `CONTRIBUTING.md` was restored by #616 .
