### ISSUE TITLE
how can i read headers or path params into a struct

### ISSUE THREAD

**Issue by Silentdoer** [http-rs/tide#504]
like req.body_json().await?;

**Comment by Fishrock123** [comment]
It seems like in the future tide will read headers into an [`http_types::Headers` struct](https://docs.rs/http-types/1.2.0/http_types/headers/struct.Headers.html).

**Comment by vkill** [comment]
> path params into a struct

use [query](https://docs.rs/tide/0.8.1/tide/struct.Request.html#method.query)   [e.g.](https://github.com/http-rs/tide/blob/master/tests/querystring.rs#L18) 

> read headers

just can read header via [header](https://docs.rs/tide/0.8.1/tide/struct.Request.html#method.header)
