### ISSUE TITLE
Uncomment and fix tests

### ISSUE THREAD

**Issue by jbr** [http-rs/tide#509]
currently two in tests/* are commented out. this issue represents the task of uncommenting them, ensuring that they continue to be relevant to tide's api, and getting them to pass. this might be fixed by one or two prs

- [ ] [wildcard](https://github.com/http-rs/tide/blob/master/tests/wildcard.rs)
- [ ] [response](https://github.com/http-rs/tide/blob/master/tests/response.rs)

**Comment by yusuke-ota** [comment]
"tests/wildcard.rs" and "tests/response.rs" were fixed.
Maybe, this issue can close.

**Comment by jbr** [comment]
Thanks @yusuke-ota!
