### ISSUE TITLE
CorsMiddleware doesn't apply headers to error responses

### ISSUE THREAD

**Issue by davidpdrsn** [http-rs/tide#525]
It seems that because of [this `?`](https://github.com/http-rs/tide/blob/master/src/security/cors.rs#L171) `CorsMiddleware` doesn't apply headers to errors. So when the error gets turned into a response the client will still get errors about a missing CORS header.

I have looked a bit at the implementation but don't see a good solution currently, because you're not able to add headers to errors. Since that would require a patch to [http_types](https://github.com/http-rs/http-types) I thought I would open an issue here first. Maybe there is an easier solution.

**Comment by rkusa** [comment]
Here is a workaround until this gets fixed. Just add this as your last middleware:

```rust
#[derive(Debug)]
struct CorsFix;
impl<State: Send + Sync + 'static> Middleware<State> for CorsFix {
    fn handle<'a>(
        &'a self,
        req: Request<State>,
        next: Next<'a, State>,
    ) -> BoxFuture<'a, Result> {
        Box::pin(async move {
            // Convert any error to a response so CORS headers can be added
            Ok(match next.run(req).await {
                Ok(res) => res,
                Err(err) => {
                    let mut res = http_types::Response::new(err.status());
                    if !res.status().is_server_error() {
                        res.set_body(err.to_string());
                    }
                    res.into()
                }
            })
        })
    }
}
app.middleware(CorsFix);
```

**Comment by rkusa** [comment]
This should btw be fixed with recent changes to tide - see also the green unit test here https://github.com/http-rs/tide/pull/546.
