### ISSUE TITLE
Re: Example code on v0.9.0 release page 

### ISSUE THREAD

**Issue by zinahe** [http-rs/tide#558]
This is in relation to #557 

Wow! Thanks for the quick action. 

But I think the code still has some issues:

1. It complains about not being able to infer the type for `res` 

```rust
assert_eq!(res.body_string().await?, "hello world".to_owned());
           ^^^ cannot infer type
```
2. Once that is fixed with `res: http::Response` then it complains about not being able to borrow `res` as `mut`. 
```rust
assert_eq!(res.body_string().await?, "hello world".to_owned());
           ^^^ cannot borrow as mutable
```
This due to [`pub async fn body_string(&mut self) -> crate::Result<String>`](https://github.com/http-rs/http-types/blob/809013933ea0b11bf4d14431fa3e7df6bab33793/src/response.rs#L333)

The following works.  But having to define `res` as `mut`, while perfectly fine when coding for an end-point, it makes little sense to me in the context of testing.

```rust
     #[async_std::test]                                                                    
     async fn hello_world() -> tide::Result<()> {                                          
         let mut app = tide::new();                                                        
         app.at("/").get(|_| async move { Ok("hello world")} );                            
                                                                                           
         let req = http::Request::new(Method::Get, Url::parse("http://computer.soup")?);   
         let mut res: http::Response = app.respond(req).await?;                            
                                                                                           
         assert_eq!(res.body_string().await?, "hello world".to_owned());                   
         Ok(())                                                                            
     }                                                                                     
```

_Originally posted by @zinahe in https://github.com/http-rs/tide/issues/557#issuecomment-635997848_

**Comment by Fishrock123** [comment]
Huh. Shouldn't `cargo` try to parse/compile the doc examples by default?

We'd happily take a PR that fixes it!

**Comment by kyrias** [comment]
@Fishrock123 This is about the examples in the GitHub release description for 0.9.0, it's nothing in the repo itself.

**Comment by Fishrock123** [comment]
I have edited https://github.com/http-rs/tide/releases/tag/v0.9.0, let me know if anything else needs to be done to it!
