### ISSUE TITLE
Secure the Apis With JWT

### ISSUE THREAD

**Issue by ferasawadi** [http-rs/tide#568]
Hello There, am writing Restful Apis usually with Python(Sanic, Flask) or With Spring boot in Java.
but i Came up with a chance to try out RUST, when i Searched around i found tide.
So here is a couple of questions that you may help me with please.
1- can we secure the Apis Using JWT? issue , parse them ?
2- is there any connectors to the Databases like Mysql, sqlite or in-memory Database (redis,mongo) or even can we use sqlite in Memory. is there any thing available in here like Hibernate, sqlalchemy?
3- what about Dockers also.

thanks for being patient, have a Good One everbody

**Comment by Fishrock123** [comment]
Hi

1. You should be able to build JWT auth on top of / or using https://github.com/chrisdickinson/tide-http-auth as a reference.
2. There may be wrappers out there, or you could probably build one easily enough on [surf](https://github.com/http-rs/surf).
3. Huh? This will run in docker like any other binary compiled to the correct target platform.

Tide is still under substantial development - if you want these things now please feel free to be the one leading the charge! :)
