### ISSUE TITLE
Use `async-trait` for traits such as `Middleware`

### ISSUE THREAD

**Issue by ZizhengTai** [http-rs/tide#576]
I was browsing the source code of [`Middleware`](https://github.com/http-rs/tide/blob/master/src/middleware.rs) and noticed that most of the async methods are defined to return a `BoxFuture`. For example, on `Middleware`:

```rust
fn handle<'a>(
    &'a self,
    request: Request<State>,
    next: Next<'a, State>,
) -> BoxFuture<'a, crate::Result>;
```

Since we are not making use of a zero-allocation custom future here, I wonder if it's more ergonomic to instead use `#[async_trait]` on the traits, and define `handle` like this:

```rust
async fn handle<'a>(
    &'a self,
    request: Request<State>,
    next: Next<'a, State>,
) -> crate::Result;
```

I'm quite new to async Rust but I think most of the time the reason to have a function return a future is either 1) to support pre-`async/await` Rust, or 2) to allow zero-allocation custom futures, both of which don't apply here. Not to mention that if we use `#[async_trait]` now, 2) will be automatically possible once actual async traits land in the language.

I'm interested in your opinions.

**Comment by jbr** [comment]
Thanks for this suggestion!
