### ISSUE TITLE
* route priority

### ISSUE THREAD

**Issue by spacekookie** [http-rs/tide#593]
Currently `serde_dir()` seems to be broken. It works if it is the only route in an app, but fails to is never routed to when it's not.

```rust
pub(crate) fn setup(app: &mut Server<StateRef>, root: PathBuf) {
    app.at("/static").serve_dir(root.join("static")).unwrap();
}
```

This works, but the following does not: 

```rust
pub(crate) fn setup(app: &mut Server<StateRef>, root: PathBuf) {
    app.at("/:owner/:repo").get(|_| async move { Ok("Hello world!") });
    app.at("/static").serve_dir(root.join("static")).unwrap();
}
```

**Comment by jbr** [comment]
I believe this is the same issue as #595 — if you add a distinct prefix to the dynamic route, like `app.at("/api/:owner/:repo").get(|_| async { Ok("hello world") });`, it will route correctly

**Comment by spacekookie** [comment]
That's not really doable for me though because I'm not building an api, I need the paths to be what users see because I'm rendering templates. The /static route needs to exist for the templates o pull in css files

**Comment by Fishrock123** [comment]
Does this work? That is, switching registration order?

```rust
pub(crate) fn setup(app: &mut Server<StateRef>, root: PathBuf) {
    app.at("/static").serve_dir(root.join("static")).unwrap();
    app.at("/:owner/:repo").get(|_| async move { Ok("Hello world!") });
}
```

`at("/:param")` should reasonably capture anything that is `/v`, `/v/`, `/v/*`, but `at("/:p/:p")` should not match just `/v` or `/v/` - if it does that's a bug, imo.

**Comment by jbr** [comment]
I've reproduced this problem and I'm not sure what the right solution is, but here's an update. Route prioritization exists in [code outside of http-rs](https://github.com/http-rs/route-recognizer/blob/master/src/lib.rs#L30-L48).

This issue can be reduced to the following failing test (using the test helpers in #601 for convenience):
```rust
#[async_std::test]
async fn static_routing() {
    let mut app = tide::Server::new();
    app.at("/:one/:two").get("two segments");
    app.at("/a/*").get("static + star");
    assert_eq!(app.get_body("/a/a").await, "static + star");
}

```

which results in

```
---- static_routing stdout ----
thread 'static_routing' panicked at 'assertion failed: `(left == right)`
  left: `"two segments"`,
 right: `"static + star"`', tests/wildcard.rs:127:5
```

Of note, route-recognizer is not order dependent, and instead uses a relative priority comparison that in this case is not what we want.

**Comment by jbr** [comment]
Update: This is fixed in route-recognizer master, so we just need them to publish a patch release

**Comment by jbr** [comment]
@spacekookie If you get a chance, could you confirm that this is fixed in tide master? Thanks!

**Comment by spacekookie** [comment]
The main branch doesn't work for me because i'm getting this error:

```
error: failed to select a version for `url`.    ... required by package `serde_urlencoded v0.6.1`    ... which is depended on by `http-types v2.2.1`    ... which is depended on by `tide v0.11.0 (https://github.com/http-rs/tide#f8373ee1)`    ... which is depended on by `octopus v0.1.0 (/home/projects/octopus)`versions that meet the requirements `= 2.1.0` are: 2.1.0all possible versions conflict with previously selected packages.

  previously selected package `url v2.1.1`
    ... which is depended on by `http-types v2.2.1`
    ... which is depended on by `tide v0.11.0 (https://github.com/http-rs/tide#f8373ee1)`
    ... which is depended on by `octopus v0.1.0 (/home/projects/octopus)`

failed to select a version for `url` which could resolve this conflict
```


My `Cargo.toml`:

```toml
[package]
name = "octopus"
description = "A lightweight web frontend for git repositories"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
tide = { git = "https://github.com/http-rs/tide" }
```

**Comment by jbr** [comment]
does cargo update resolve that?
