### ISSUE TITLE
I'm lost between tide::Response, tide::http::Response and http_types::Response

### ISSUE THREAD

**Issue by zinahe** [http-rs/tide#602]
Hi,

The title says it all. I understand that tide, true to it's name, is a moving target. Which one of the three is staying and which ones are going away? 

Thanks,

Zinahe A.

**Comment by jbr** [comment]
tide::http::Response and http_types::Response are _identical_. tide re-exports http_types as tide::http.

Tide applications are built using tide::Responses. Tide itself is built using http_types::Responses.  If you're not sure which to use, you probably want a tide::Response.  This is stable and there are no plans I know of for any of the three to go away. Does that help?

**Comment by zinahe** [comment]
Thanks. That does help indeed.
