### ISSUE TITLE
Regression on decoding query parameters (http-types issue)

### ISSUE THREAD

**Issue by xorxsan** [http-rs/tide#605]
Hi,

   I found an issue in which I cannot longer send arrays or maps in query parameters:
`curl -v -g "http://localhost:5000/v1/endpoint?requestor=test&quantities[0]=100&quantities[1]&selections[Width]=narrow&selections[Heigh]=tall"` fails with `missing field 'selections'*`. This was working on versions 0.8.1 and 0.9.0 and it fails both with versions 0.10.0 and 0.11.0.
Example code:
```
#[derive(serde::Deserialize)]
struct FailingParams {
    requestor: String,
    selections: std::collections::HashMap<String, String>,
    quantities: Vec<i32>,
}

async fn handle_endpoint(req: tide::Request<()>) -> tide::Result {
    let queries: FailingParams = req.query()?;
    let mut res = tide::Response::new(tide::StatusCode::Ok);
    res.set_body("ok");
    Ok(res)
}

#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    let mut address = String::from("127.0.0.1:");
    address.push_str("5000");

    let mut app = tide::new();
    app.at("/").get(|_| async { Ok("Healthy") });
    app.at("/v1/endpoint").get(handle_endpoint);
    app.listen(address).await?;
    Ok(())
}
```
Have I forgotten to include something?

Thanks!

**Comment by jbr** [comment]
Yes, this does seem to be a regression.  Previously, tide was using serde_qs, which is correct: https://github.com/http-rs/tide/blob/c282e92ed9a1a76dec17066daef77543fafa3ebf/src/request.rs#L289, but as of ef42cc18f3bb75570760971e71d481ecf0eb9a6c, switched to using http_types::Request::query, which uses serde_urlencoded, which is not correct
