### ISSUE TITLE
No body content for StatusCode::InternalServerError

### ISSUE THREAD

**Issue by nwilcox93** [http-rs/tide#614]
https://github.com/http-rs/tide/blob/293610b7db1ab9a69a338e7d7db5033ae32bc376/src/server.rs#L416

When returning an Err(http_types::Error) inside a handler that returns a tide::Result, the message for the error is not displayed in the browser if the status is StatusCode::InternalServerError.  I can work around this by returning Ok(Response) with StatusCode::InternalServerError. It seems like it is an anti-pattern to return Ok(Response) when an error occurred on the server.  Just looking for some clarification the correct approach.

Thanks!

**Comment by jbr** [comment]
See #570 for some changes related to this. In short, error handling is likely changing substantially in the near future

**Comment by jbr** [comment]
The solution for this in tide >= 0.12 is to add a middleware that catches responses with an attached error and builds a string body with it, something like:
```rust
    app.middleware(After(|mut res: Response| async {
        if let Some(err) = res.take_error() {
            res.set_body(err.to_string()) // or json, or html, etc, whatever is appropriate for your app
        }
        Ok(res)
    }));
```
