### ISSUE TITLE
GraphQL example doesn't work when tried in separate repo

### ISSUE THREAD

**Issue by vladinator1000** [http-rs/tide#626]
## Bug Report
The Request struct doesn't have a "builder" function when I try to copy the graphql example.

#### Current Behavior
Can't use the example as a starting point. If you clone the Tide repo it works just fine but if you try to add the library in your project as a crate dependency it doesn't compile.

#### Code/Gist
I re-wrote the example like this and it works when you use a mutable response
https://github.com/vladinator1000/tide-gql/

```rs
pub async fn handle_graphiql(_: crate::Request) -> tide::Result {
    let mut response = Response::new(200);
    response.set_body(graphiql::graphiql_source("/graphql"));
    response.set_content_type(mime::HTML);
    Ok(response)
}
```

#### Expected behavior/code
Examples should work outside the Tide repo when users try the library in their own project.

#### Environment
nightly-x86_64-unknown-linux-gnu (WSL)

#### Possible Solution
https://github.com/vladinator1000/tide-gql/

#### Additional context/Screenshots
Tide is lookin sweeet, keep up the good work 😍

**Comment by jbr** [comment]
Git master is slightly different from the most recent release, which is 0.11. You can either use master (a development branch) or use the examples in the release tag: https://github.com/http-rs/tide/tree/v0.11.0
