### ISSUE TITLE
Body::from_file() may truncate file length on 32-bit architectures

### ISSUE THREAD

**Issue by chputnam** [http-rs/tide#628]
On 32-bit architectures, tide::http_types::Body::from_file() returns an incorrect file length on files larger than 2^32 bytes.

Current behavior: The function retrieves the file length from async_std::fs::Metadata, which returns the length as a u64. Then the function casts the length to a usize. This works fine on 64-bit architectures, but drops the upper 32 bits of the length on 32-bit architectures. For any file longer than 2^32-1 bytes, the server will report the wrong size to the client.

This may not cause serious problems in practice since it's possible that web clients will continue to receive data even when the byte count exceeds the declared Content-Length, but it's clearly incorrect.

Expected behavior: Body::from_file() should report the correct file length regardless of the underlying architecture.

Possible solution: Body.length should be defined as Option<u64> rather than Option<usize>. That's probably a lot of work, so a reasonable stopgap would be to detect whether the size of the file is greater than usize::MAX, in which case Body.len could be set to None.

**Comment by chputnam** [comment]
Looks like the markup system ate some of my message. Possible solution should be:

`Body.length` should be defined as `Option<u64>` rather than `Option<usize>`.

**Comment by yoshuawuyts** [comment]
Thanks for raising this @chputnam. You're entirely right, we have an issue open for this in `http-types` and will make it part of `http-types` v3.0.0. Closing this issue in favor of https://github.com/http-rs/http-types/issues/164
