### ISSUE TITLE
The async wrapper may not be needed here

### ISSUE THREAD

**Issue by fundon** [http-rs/tide#629]
https://github.com/http-rs/tide/blob/e994b2ebbaa5a1ebe6849bff720adff89dae1fb5/src/log/middleware.rs#L86

**Comment by yoshuawuyts** [comment]
@fundon thanks for opening. That's interesting; how would you rewrite it?

**Comment by jbr** [comment]
I think the suggestion is
```rust
Box::pin(self.log(ctx, next))
```
I’ve been assuming that the compiler treats those equivalently. Does adding `async move { x.await }` cost anything over `x`?

**Comment by yoshuawuyts** [comment]
@jbr oh, no that should compile down to the same thing. We can def do that (:

**Comment by jbr** [comment]
That’s what I figured, in which case this is a readability/style thing, and neither seems clearly better or worse to me

**Comment by fundon** [comment]
They compile the same results. We just follow a style. Thanks.

https://rust.godbolt.org/z/vZVt_R
