### ISSUE TITLE
The 0.12.0 release commit is wrong.

### ISSUE THREAD

**Issue by Fishrock123** [http-rs/tide#654]
https://github.com/http-rs/tide/releases/tag/v0.12.0 points to https://github.com/http-rs/tide/commit/261038d7487b1bef475e01ea012c1b44a6e63ae9 which _seems_ wrong, but given that the version on crates.io is indeed `0.12.0` this is clearly wrong as the `Cargo.toml` version number would have needed to be bumped. As it stands, `Cargo.toml` in this repo still has `version = "0.11.0"`.

@yoshuawuyts

**Comment by yoshuawuyts** [comment]
Pushed!

**Comment by Yarn** [comment]
For anyone else that comes across this bf135bd seems like a good guess at the right commit. Not sure though.

**Comment by Yarn** [comment]
actually, bc026d1220626b89d590348e608c7fde3c0bd0de maybe
