### ISSUE TITLE
Minor documentation error for Route::serve_dir?

### ISSUE THREAD

**Issue by VanillaBrooks** [http-rs/tide#659]
## Question

The docs for `Route::serve_dir` have this example:

https://github.com/http-rs/tide/blob/50bc628a2645b71d4b422f6b2b5fe0f4b6085abd/src/route.rs#L118-L132

Most notably, it says:  
```
/// Serve the contents of the local directory `./public/images/*` from
/// `localhost:8080/images/*`
```

Isn't this code actually serving the local directory `images/*` to  `localhost:8080/public/images`?

**Comment by jbr** [comment]
Nice catch! The documentation line is correct and the code example is backwards

**Comment by VanillaBrooks** [comment]
I was going to drop a quick PR for this but I noticed your DCO link [here](https://github.com/http-rs/tide/blob/master/.github/CONTRIBUTING.md#developer-certificate-of-origin) is broken. Any idea where the DCO is ?

**Comment by jbr** [comment]
Relevant: https://github.com/http-rs/tide/pull/648
