### ISSUE TITLE
Rename Server::middleware to Server::with

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/tide#665]
Initially the `Server::middleware` method was chosen because `Server::use` isn't possible as it's a reserved keyword. The idea was to resemble Express's choice of naming. So instead of using a verb I chose to just name it what it is in the expectation that we could later find a suitable verb.

As I was doing some work with the `tracing` crate today I noticed they use the `with` method to compose various [`Layer`s](https://docs.rs/tracing-subscriber/0.2.9/tracing_subscriber/layer/trait.Layer.html). This is much the same as our middleware, and actually fits well. The `with` function name in the stdlib is also canonically used to add a function that the item is passed through first.

So I'd like to propose we rename `Server::middleware` to `Server::with`, bringing it in line with the other `Server` methods such as `Server::at`, `Server::nest`, `Server::listen`.

## Example

With this change:
```rust
let mut app = tide::new();
app.with(MyMiddleware::new());
app.at("/").get(|_| async move { Ok("hello chashu") });
app.listen("localhost:8080").await?;
```
Without this change:
```rust
let mut app = tide::new();
app.middleware(MyMiddleware::new());
app.at("/").get(|_| async move { Ok("hello chashu") });
app.listen("localhost:8080").await?;
```

## Future

The expectation is that we'll eventually have async closures, which would allow us to author this with anonymous middleware from closures, which would make `with` an even more accurate nomer.

```rust
let mut app = tide::new();
app.with(async |req, next| {
    println!("incoming {} method", req.method();
    next().await
});
app.at("/").get(async try |_| "hello chashu");
app.listen("localhost:8080").await?;

**Comment by jbr** [comment]
Would this also entail `app.at("/").with(SomeMiddleware::new()).all(|_| async { Ok("") })`?

**Comment by Fishrock123** [comment]
Fwiw, I doubt going forward we'll have middleware be named `{Thing}Middleware`. I was thinking of switching `tide_compress::CompressMiddleware` to something like `tide_compress:Compress` the other day., following more where built in middleware in Tide and Surf seem to be going.

That being said, I don't object to this if it's consistent with rust, makes enough sense to me.

**Comment by yoshuawuyts** [comment]
@jbr yeah!

**Comment by Fishrock123** [comment]
@yoshuawuyts I think you were thinking about `surf::middleware::Redirect`? 😄

**Comment by yoshuawuyts** [comment]
@Fishrock123 haaa, yes probably!
