### ISSUE TITLE
tide 0.13.0 doesn't compile in linux-arm

### ISSUE THREAD

**Issue by prabirshrestha** [http-rs/tide#673]
https://github.com/prabirshrestha/rblog/runs/938464387

```
error[E0277]: the trait bound `std::sync::atomic::AtomicBool: session::_::_serde::Deserialize<'_>` is not satisfied
##[error]  --> /cargo/registry/src/github.com-1ecc6299db9ec823/async-session-2.0.0/src/session.rs:65:5
   |
65 |     destroy: Arc<AtomicBool>,
   |     ^^^^^^^ the trait `session::_::_serde::Deserialize<'_>` is not implemented for `std::sync::atomic::AtomicBool`
   |
   = note: required because of the requirements on the impl of `session::_::_serde::Deserialize<'_>` for `std::boxed::Box<std::sync::atomic::AtomicBool>`
   = note: required because of the requirements on the impl of `session::_::_serde::Deserialize<'_>` for `std::sync::Arc<std::sync::atomic::AtomicBool>`
   = note: required by `session::_::_serde::de::MapAccess::next_value`

error: aborting due to 3 previous errors
##[error]aborting due to 3 previous errors
For more information about this error, try `rustc --explain E0277`.
error: could not compile `async-session`.
##[error]could not compile `async-session`.
```

**Comment by yoshuawuyts** [comment]
cc/ @jbr Do you think we can we find a way around serializing the atomic bool in `async-session`? IIRC ARM may be polyfilling atomics using spinlocks; it seems there may be a strange interaction there.

Not sure what the right solution here is. Perhaps cast the atomic bool to a regular bool first when serializing? Maybe using a `Arc<Mutex<Bool>>` achieve much the same result without the serialization problems -- assuming there's no contention this should be fairly fast as well.

**Comment by jbr** [comment]
Yeah, in this case we don't need to serialize the AtomicBool, so we can avoid this issue. I'll fix this posthaste.

This seems like a serde bug, though, since [they do the serialization of atomicbool](https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L857-L883)

**Comment by jbr** [comment]
Just released https://github.com/http-rs/async-session/releases/tag/v2.0.1 so if you cargo update tide should work on arm again

**Comment by prabirshrestha** [comment]
it works. thanks for the quick fix. might be good to have ci that compiles linux arm.
