### ISSUE TITLE
Logging not working on Windows

### ISSUE THREAD

**Issue by alexanelli** [http-rs/tide#674]
#### Environment
- Rust toolchain version(s): rustc 1.45.0 (5c1f21c3b 2020-07-13)
- OS: Windows 10
- Terminal: Windows Terminal running Git bash 

tide::log doesn't seem to be giving me the expected output on windows.  tide::log::info! and other log level macros display nothing. dbg! also displays nothing.

Output on Windows:
```
{"level":30,"time":1596477825885,"msg":"Logger started","level":Info}
{"level":30,"time":1596477825890,"msg":"Server listening on http://127.0.0.1:7000"}
{"level":30,"time":1596477842598,"msg":"<-- Request received","method":POST,"path":/get-file}
{"level":40,"time":1596477842599,"msg":"--> Response sent","method":POST,"path":/get-file,"status":422,"duration":163.7µs}
```

Output on Mac:
```
tide::log Logger started
    level Info
tide::listener::tcp_listener Server listening on http://127.0.0.1:7000
tide::log::middleware <-- Request received
    method POST
    path /get-file
my_crate THIS DOES NOT DISPLAY ON WINDOWS
tide::log::middleware --> Response sent
    method POST
    path /get-file
    status 200
    duration 75.050985ms
```

**Comment by jbr** [comment]
Are you running as --release on windows? The logger [changes some defaults](https://github.com/lrlna/femme/blob/master/src/lib.rs#L57-L60) when running in release vs in development

**Comment by alexanelli** [comment]
ok awesome thank you.  We were running as release and running without the --release flag did make the formatting line up.  I'm still having trouble getting logs out to the console though.  I'll include some snippets and see if there's something obvious I'm missing.

here's some rust if that's helpful:
in our main function:
```rust
fn main() {
    ...
    smol::run(async {
        
        tide::log::start();
        let mut app = tide::new();
        app.at("/get-file").post(get_file);

        app.listen(listen_addr).await.unwrap();
    });
}
```

in the get_file function:
```rust
async fn get_file(mut req: Request<()>) -> tide::Result<Response> {

    let req: MyRequest = req.body_json().await?;

    tide::log::info!("testing");
    let path = Path::new(&req.path);
    tide::log::info!("{:#?}", path);
    ...
}
```

and here's the corresponding logs (formatting now is what we expected, but I'm not getting any logs out)
```
tide::log Logger started
    level Info
tide::listener::tcp_listener Server listening on http://127.0.0.1:7000
tide::log::middleware <-- Request received
    method POST
    path /get-file
tide::log::middleware --> Response sent
    method POST
    path /get-file
    status 422
    duration 1.1734ms
```

**Comment by jbr** [comment]
It looks like maybe the body_json isn't parsing correctly, so you're not getting to the log line. Try adding a log message above the body_json line or don't use a ? on the body_json Result, like
```rust
let my_request: tide::Result<MyRequest> = req.body_json().await;
```

**Comment by alexanelli** [comment]
Right that makes sense 🤦‍♂️  we were using a windows style path on this machine which wasn't deserializing properly because of the back slashes in the path. If we send the path without backslashes it does deserialize properly.  

The issue we're still having though is that we can't send a normal windows backslash style path like `C:\docs\test.txt` because it's not valid json.  If we escape the backslashes like `C:\\docs\\test.txt` the body_json function doesn't un-escape the string.

**Comment by jbr** [comment]
I'm not sure if it's a tide issue but I'm happy to try to help. I'd need to see the definition of the MyRequest struct and any arguments/annotations for the serde derive. body_json just calls serde_json::from_str, so this is either a problem with your usage or a problem with serde_json

**Comment by alexanelli** [comment]
Thank you so much for the time and attention on this.  The problem ended up being a mistake on our end.
