### ISSUE TITLE
Server-sent events dropped when serving multiple clients concurrently

### ISSUE THREAD

**Issue by masonforest** [http-rs/tide#676]
## Bug Report
Server-sent events are being dropped when serving multiple clients concurrently.

#### Current Behavior

1. Run `git clone git@github.com:masonforest/tide_bug_676.git`
2. Run `cd tide_bug_676`
3. Run `cargo run`
4. Open one tab and visit `http://localhost:8080/`and see the counter increment as expected
5. Open a second tab and visit `http://localhost:8080/` and see that the tabs alternate when incrementing

#### Code/Gist

https://github.com/masonforest/tide_bug_676

#### Expected behavior/code

Both tabs increment every value.

#### Environment

- Tide Version: `master/0.13.0`
- Rust toolchain version(s): stable-x86_64-apple-darwin
- OS: OSX 10.15.5

**Comment by jbr** [comment]
My understanding is that this is the intended api of async-channels. Try https://docs.rs/broadcaster/ for the behavior you expect

**Comment by jbr** [comment]
See https://github.com/masonforest/tide_bug_676/pulls/1

**Comment by jbr** [comment]
Closing this issue, please reopen if broadcaster does not resolve

**Comment by masonforest** [comment]
You're right! That's just what I was looking for! Thanks so much! 😀

**Comment by jbr** [comment]
This is something [tide channels](https://blog.yoshuawuyts.com/tide-channels/) will hopefully make much more usable soon
