### ISSUE TITLE
Update AppState

### ISSUE THREAD

**Issue by TsumiNa** [http-rs/tide#688]
## Question
Hi, I'm trying to use the tide to build a `JsonWebKey` based authorization system. The system should fetch the `jwk`s from a well-know-list somewhere and then try to use these to decode the `Bearer` token in the `Request`.

Since `jwk` may have an expired time and need to refresh itself, so is there any way to update the data in the AppState?

The imagination may be something like this:
```rust
let app = tide::with_state(AppState {need_refresh_data});
app.at("/").get(|req: Request<AppState>| async move {
    ...
    req.state().need_refresh_data.update().await;  // data will be updated in place
    ...
})
```

**Comment by jbr** [comment]
You'll probably want something like (rough sketch, not entirely sure what `need_refresh_data.update().await` is doing)
```rust
use async_std::sync::{Arc, RwLock};
#[derive(Clone)]
struct AppState {
    jwk_data_of_some_sort: Arc<RwLock<HashSet<Jwk>>>
}

fn main() {
    let app = tide::with_state(AppState {need_refresh_data});
    app.at("/").get(|req: Request<AppState>| async move {
        // ...
        let data = req.state().jwk_data_of_some_sort.write().await.update().await;
        //...
    })
}
```

**Comment by TsumiNa** [comment]
@jbr Thanks! I will try it 👍
