### ISSUE TITLE
Reminds me of go-chi

### ISSUE THREAD

**Issue by pkieltyka** [http-rs/tide#699]
Hi, I’m the author of go-chi. Tide looks awesome and reminds me very much of the same architecture and router design in go-chi — even the method naming and example. Just wondering if there was any inspiration from go-chi? I’ll def try tide once I start getting more into Rust

**Comment by yoshuawuyts** [comment]
Hi, glad you like Tide! It's the first time I'm hearing of go-chi; I don't believe anyone's brought it up during design discussions before either.

Though we did try to create a design in the spirit of Flask/Sinatra/Express/Koa, so perhaps we've built from shared inspiration?

**Comment by pkieltyka** [comment]
Neat! Cool to hear we converged on similar ideas :) nice work btw
