### ISSUE TITLE
Add `Server::listen_with` to invoke logic _after_ the server has started

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/tide#712]
At work we were having an ordering issue where we want to trigger something once the server has started listening. However currently there is no good way of defining that since the `listen` method just waits until the server shuts down.

So I propose we add an additional `Server::listen_with` method that takes a callback as the second argument. From there we should be able to share how and what the server is listening on.

## Example

This is the logic we use at work: the "server listening" message is emitted before we actually listen. This is problematic for UDS connections since trying to send a message on a non-existing file will fail, which is slightly different from TCP which _is_ able to retry.

```rust
    // NOTE: This println is essential for the correct working of the client.
    info!("Started http server");

    // Start the Tide server and log the server details.
    // TODO: Tide should have a panicking listen_unix impl.
    if let Some(path) = opts.unix_path() {
        app.listen(&*format!("http+unix://{}", path)).await?;
    } else {
        app.listen((&*opts.host, opts.port)).await?;
    }
```

**Comment by Fishrock123** [comment]
Heh, ironically we ran into this just the other day at eaze. I'd certainly be in favor of this.

**Comment by yoshuawuyts** [comment]
Put out https://github.com/http-rs/tide/pull/740 which supersedes #724.
