### ISSUE TITLE
upgrade async-sse

### ISSUE THREAD

**Issue by danjenson** [http-rs/tide#718]
Version 4.0.0 of async-sse has this [issue](https://github.com/http-rs/async-sse/issues/10), which is apparently fixed in 4.0.1, can you upgrade in your dependencies?

**Comment by Fishrock123** [comment]
@daleione please run [`cargo update`](https://doc.rust-lang.org/cargo/commands/cargo-update.html) (or delete your `Cargo.lock`).

**Comment by danjenson** [comment]
thx
