### ISSUE TITLE
Serving from multiple directories

### ISSUE THREAD

**Issue by VersBinarii** [http-rs/tide#719]
Hello,
Currently its possible to specify a single directory from where the assets are served.
Is there a way to specify multiple `server_dir`s to serve assets from?

**Comment by AlecDivito** [comment]
I believe the only way to serve another directory is by using a new path. An example would look like:

```rust
    let mut app = tide::new();
    app.at("/").get(|_| async { Ok("visit /src/*") });
    app.at("/src").serve_dir("src/")?;
    app.at("/test").serve_dir("test/")?;
    app.listen("127.0.0.1:8080").await?;
```

I don't believe there is currently a way to serve multiple directories from the same route.

**Comment by Fishrock123** [comment]
If you really need this, I would recommend looking at the source for `serve_dir` and making your own endpoint for this.

**Comment by VersBinarii** [comment]
Thanks for the suggestions. I will try it out
