### ISSUE TITLE
How to improve performance of Tide?

### ISSUE THREAD

**Issue by flyinmind** [http-rs/tide#729]
The simplest example, run on windows 10, intel X64 8cores, 1.6Ghz, 8G mem.
Client is baton( realized in Go ), on the same PC.
Tide + baton ==> about 53000/s
ActixWeb + baton ==> more than 70000/s
Almost 25% gap.
**How to improve it in Tide?** 
In actix-web, can set works by ".workers(8)" to improve it obviously.
Thanks!

```
use tide;

#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    //tide::log::start();
    let mut app = tide::new();
    app.at("/").get(|_| async { Ok("Hello, world!") });
    app.listen("127.0.0.1:8080").await?;
    Ok(())
}
```

**Comment by jbr** [comment]
Although performance is certainly a long term priority, we are not currently at a point of development where we are focused on benchmarks comparing to other rust frameworks. If the difference in performance described above is currently a large concern in the short term, tide is likely not ready for your use case.

**Comment by Fishrock123** [comment]
That being said, if you can get profiles / flamegraphs, I'd love to look through them and see what shows up and if there are any easy wins that don't impact our API.

**Comment by flyinmind** [comment]
I have no flamegraphs. It is only a simple comparation.
And I don't care 25% gap so much.
Because I want to find a web client and  web server to realize a micro-service framework.
I tried so many tools. Finally I decide to use crates based on async-std.

**Comment by jbr** [comment]
Async-std already runs with one worker per core, as reported by the operating system.  Although this [can be tuned](https://docs.rs/async-std/1.6.5/async_std/#runtime-configuration), the default number is correct for most computers already. In general, if there were an easy way to improve the performance of tide or async-std, we would try to do it automatically.
