### ISSUE TITLE
'//' path produces async-h1 error, probably from being treated as a protocol-relative URL

### ISSUE THREAD

**Issue by etherealvisage** [http-rs/tide#733]
Consider the following minimal tide server:
```rust
#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    tide::log::start();
    tide::new().listen("127.0.0.1:2000").await?;
    Ok(())
}
```

If we then run curl against it:
```
~$ curl localhost:2000// 
curl: (52) Empty reply from server
```

The logging output contains:
```
tide::listener::tcp_listener async-h1 error
    error empty host
```

After guessing from the empty host bit that it's treating "//" as a protocol-relative URL; and we can confirm this by curling `localhost:2000//test/a/b/c`: the logging output says:

```
tide::log::middleware <-- Request received
    method GET
    path /a/b/c
```

I haven't gone digging for where this might be happening, but thought I'd open this issue in case it's a quick fix for someone else :-)

**Comment by Fishrock123** [comment]
Should be fixed in the next `async-h1 release
