### ISSUE TITLE
Add a '.json()' method to Response

### ISSUE THREAD

**Issue by cbrownsey** [http-rs/tide#741]
This is a small and basic addition that should be simple to implement with the code base that already exists,
Currently to send a serializable struct as JSON, it requires code similar to this
```rust
Response::builder(200)
    .body(serde_json::to_string(&data))
    .content_type(tide::http::mime::JSON)
    .build()
```
However, if a `json` function were to be added, with a signature similar to `fn json<T: Serialize>(status: S, data: &T) -> ResponseBuilder`, that sets the content type and serializes the data, then syntax like this would be much more convenient.

```rust
Response::json(200, &data);
```

The implementation and tests should be trivial to write, but I wanted to be sure that this isn't an unwanted feature

**Comment by jbr** [comment]
We currently support this with `Ok(Response::builder(200).body(Body::from_json(&data)).build())` or `Ok(Body::from_json(&data))`. At least as of now, we're keeping body builders on Body

**Comment by Fishrock123** [comment]
Note that if your json is a [`serde_json::Value`](https://docs.serde.rs/serde_json/enum.Value.html), such as from [`json!({})`](https://docs.serde.rs/serde_json/macro.json.html), you can pass it directly to `.body()` - i.e. `.body(json!({}))`

**Comment by yoshuawuyts** [comment]
I can see the appeal for having a direct `ResponseBuilder::body_json` method though; if not for convenience, then for discovery. But it would probably require adding it for all supported types. I'd imagine this would look something like this:

```rust
Response::builder(200)
    .body_json(&data)
    .build()
```

**Comment by Fishrock123** [comment]
I think if we did that here and Surf we'd want it to be more like Surf 1.x / Request -- i.e. just shorthand `.json()`.
