### ISSUE TITLE
Is there a tide roadmap?

### ISSUE THREAD

**Issue by kennetpostigo** [http-rs/tide#748]
Hi 👋

I'm a user of tide, and really enjoy how pleasant it makes building webservers in rust! However I haven't been able to find much about what is being worked on for tide or rather what the focus for the future of tide is in the near and long term. 

Does the http-rs team have a roadmap for what next for tide?

**Comment by yoshuawuyts** [comment]
Hey @kennetpostigo, thanks for asking! -- If you'd asked this question a few weeks ago, the answer would've been "no" -- but we've been hard at work to clarify what we're focusing on, and where we're headed.

## Themes

We have two primary focuses right now, with a third goal that we're gradually definining:

1. **Improve the processes around Tide**: we're working on scaling the project from just me, to a core team. And going through the motions of enabling people to make decisions, defining goals, communicating directions, and also: roadmaps. This is something I'm spearheading.
2. **Build out protocol support for Tide**. At the core of every feature we build are the web protocols: HTTP, Multipart, Headers, WebSockets, etc. We're focusing on building a solid foundation of protocols, so we can build out ergonomic layers on top of them.
3. **API design / ergonomics**. This is currently still in the planning phase and depends on "protocol support" first. But the idea is that we want to provide good ergonomics for Tide, and should create flows to match. I can imagine this may require story boarding various scenarios, and ensuring that every step along the way is just right.

## Initiatives

This is the closest we have to a roadmap right now. We've started to collect various high-level goals, and are breaking them down into work we can do.

![Screenshot 2020-11-27 15 51 04](https://user-images.githubusercontent.com/2467194/100461043-805b6d80-30c8-11eb-86e8-099b61780da5.png)

## Conclusion

I hope this provides a useful snapshot of our current thinking and planning.  One thing we haven't quite figured out yet is the process of creating tracking issues, and creating ways for more people to contribute on these larger efforts -- but we're aware that this is something we need to address and definitely are planning to do so. Perhaps a useful step in getting there would be to open up the roadmap for everyone to access?

Anyway, I hope this answers your question!

**Comment by kennetpostigo** [comment]
@yoshuawuyts This is really encouraging to see, and I think the current users of tide would be relieved to see this! To a certain degree it seems like the project is at a stand still or just in maintaining what is there. Unless you join the discord and zulip. This clears things up a lot, thanks for sharing and answering my question.
