### ISSUE TITLE
Deserializing an array of form items

### ISSUE THREAD

**Issue by cschmatzler** [http-rs/tide#773]
Hi,

first of all, hope you all had a happy, healthy start to the new year.
I am struggling making forms work. In particular, I have a form that includes a list of items that can be added in the front end using AlpineJS.

In particular, my Askama template looks like this:
```html
<div x-data="{ items: {{ items }} }">
    <form action="/application/workshop/dashboard" method="POST">
        <template x-for="item in items" :key="item">
            <input type="text" x-model="item" name="items[]">
        </template>
        <button type="button" x-on:click="items.push('')">Add</button>
        <button type="submit">Submit</button>
    </form>
</div>
```

The `items` template field is simply a `Vec<&'a str>` that I convert to single-quoted JSON and initial render works beautifully, so does adding a field. In other frameworks I have used, such as Laravel, using the `items[]` syntax for input names works and deserializes the form into an array.

Using Tide (`0.15.0` on rustc `1.49.0 stable`), I am getting an error.
My routing code is as follows:
```rust
pub async fn post(mut request: Request) -> tide::Result {
    let items: Vec<String> = request.body_form().await?;
    println!("{:?}", items);

    Ok("".into())
}
```

This unfortunately errors with 
```txt
tide::log::middleware Client error --> Response sent
    message invalid type: sequence, expected a string
    error_type serde::de::value::Error
    method POST
    path /application/workshop/dashboard
    status 422 - Unprocessable Entity
    duration 21.252018ms
```

Replacing `request.body_form()` with `request.body_string()` results in the server printing `"items%5B%5D=test&items%5B%5D=test2"`, which to me looks like the request is sent and encoded correctly.
Now, how can I make this work? I would rather not add extra JavaScript and `POST` a JSON object when `application/x-www-form-urlencoded` should work for this problem.

Is this something that serde just does not support or am I being blind with something?

Cheers and thank y'all

**Comment by cschmatzler** [comment]
Okay, my original question was kinda stupid, so here is the updated one:
```
#[derive(Debug, Deserialize)]
pub struct RequestBody {
    items: Vec<String>,
}

[...]
    let body: RequestBody = request.body_form().await?;
    println!("{:?}", body);
[...]
```

results in

```
tide::log::middleware Client error --> Response sent
    message missing field `items`
    error_type serde::de::value::Error
```

I am using `serde_urlencoded` version `0.7.0`.

It seems that `items[]` is not recognized by serde as the `items` field?

If this is an issue more related to serde than tide you can close this and I will post over there.

**Comment by Fishrock123** [comment]
@cschmatzler Can you report this to https://github.com/nox/serde_urlencoded? This is almost certainly it's issue and not Tide's.

**Comment by Fishrock123** [comment]
Closing here, we can re-open if it is indeed an issue on our end.

**Comment by Fishrock123** [comment]
Here is a minimal tide-less reproduction:

```rust
#[derive(Debug, serde::Deserialize)]
pub struct RequestBody {
    items: Vec<String>,
}

pub fn main() {
    let body: RequestBody = serde_urlencoded::from_str("items%5B%5D=test&items%5B%5D=test2").unwrap();
    
    println!("{:?}", body);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ede239b1ae6f02e6211ea2dbccb0e3dc
