### ISSUE TITLE
How to route unknown paths?

### ISSUE THREAD

**Issue by silvioprog** [http-rs/tide#783]
Hi.

I'm trying to write a reverse proxy example (https://github.com/http-rs/tide/pull/784), but I don't know how to route all possible paths. Consider the following example:

```rust
app.at("*") ... ;
```

now, take a look this tests below:

```bash
curl http://localhost:8080/test
ok
curl http://localhost:8080/
404
curl http://localhost:8080
404
```

Well, since wildcard allows anything, it should return `ok` in ` ` and `/` too. 😕

Thank you!

**Comment by jbr** [comment]
Is tide the right tool for a reverse proxy, vs using async-h1 directly?

**Comment by silvioprog** [comment]
@jbr It will be just a simple just to show how a tide-based server can handle reverse proxy.

**Comment by silvioprog** [comment]
@jbr It will be just a simple example just to show how a tide-based server can handle reverse proxy.

**Comment by christoth** [comment]
I'm also trying to create a simple tide+surf based reverse-proxy.

I experienced the same behaviour and while hoping for the same expected behaviour...

The work-around I used was:
`app.at("/").all(move |mut client_request: Request<()>| async move { ... });`
`app.at("*").all(move |mut client_request: Request<()>| async move { ... });`

That combination should route all your unknown paths.

**Comment by jbr** [comment]
Out of curiosity to understand this use case, do you have other routes in addition to these? If not, using tide will be slower than using async-h1 directly as a reverse proxy

**Comment by Fishrock123** [comment]
This is useful for custom 404's.

**Comment by christoth** [comment]
Thanks for the guidance! 
I'm working on an async-h1 reverse proxy example. It's pretty basic, as I'm learning Rust.

**Comment by spikecodes** [comment]
This would be a great feature!

**Comment by jbr** [comment]
@spikecodes Which, a reverse proxy or `*` matching `/`?

**Comment by spikecodes** [comment]
My bad, I meant the reverse proxy example. I now see though that it's a separate issue: #784

**Comment by yoshuawuyts** [comment]
This likely needs to be fixed in `route-recognizer`; I've filed an issue there: https://github.com/http-rs/route-recognizer/issues/45.

**Comment by maxcountryman** [comment]
Is there a preferred method for showing a 404 page when a route isn't found with Tide today?
