### ISSUE TITLE
bad port in example

### ISSUE THREAD

**Issue by mvolkmann** [http-rs/tide#786]
The example at https://docs.rs/tide/0.15.0/tide/ listens on port 8080, but the curl commands below the code to demonstrate its usage send requests to port 8000.

**Comment by phungleson** [comment]
It seems to be an easy fix, which one is more preferable, `8080` or `8000`?

`8080` seems to have more results when I did a quick search?

**Comment by dariusc93** [comment]
`8080` is usually more common but either or is generally used.

**Comment by mvolkmann** [comment]
I don’t have a preference. You could pick something uncommon just to avoid conflicting with other servers ... like 8123.

**Comment by phungleson** [comment]
It seems to be fixed in the latest version https://docs.rs/tide/0.16.0/tide/index.html

Probably good to close this now?
