### ISSUE TITLE
can't get a simple post route to compile

### ISSUE THREAD

**Issue by mvolkmann** [http-rs/tide#788]
I think what I'm doing matches an example I found, but I'm having no luck getting this simple example to compile.
See the comments about the compiler errors I am seeing here:
https://github.com/mvolkmann/rust-tide-demo/blob/master/src/main.rs#L58

**Comment by jbr** [comment]
you need to return a Response, but this code `tide::Response::new(200).body_json(&dog).unwrap();` returns () because of the semicolon. you want something like 

```rust
let response = tide::Response::new(200);
response.set_body(Body::from_json(&dog)?);
response
```

Or

```rust
tide::Response::builder(200)
    .body(tide::Body::from_json(&dog)?)
    .build()
```

Unrelated to the question, using `unwrap()` in an endpoint is not recommended. Use ? instead.

**Comment by jbr** [comment]
The current documentation is [here](https://docs.rs/tide/0.15.0/tide). The blog post cited in the comment is out of date and is not a living document that represents current apis.

**Comment by mvolkmann** [comment]
Thanks for the feedback! I have two more errors related to this that I can't figure out. See the "// Error" comments here:
https://github.com/mvolkmann/rust-tide-demo/blob/master/src/main.rs#L58

**Comment by pepoviola** [comment]
Hi @mvolkmann, I think the issue there is that you are returning a `Response` instead a `Result` also as Jacob mention using `unwrap` is not recommended so I change your code to use `?`

Can you try this snippet

```
   app.at("/dog")
        .post(|req: Request<State>| async move {
            let dog: Dog = req.body_json().await?;
            let mut dog_map = &req.state().dog_map;
            dog_map.insert(dog.id, dog);
            let res = tide::Response::new(200);
            res.set_body(Body::from_json(&dog)?);
            Ok(res)
        });
```

Thx!

**Comment by jbr** [comment]
Oh whoops, that was my mistake. I've updated my comment

**Comment by mvolkmann** [comment]
That gives me an error on the line `let dog: Dog = req.body_json().await?;` that says "cannot borrow `*dog_map` as mutable, as it is behind a `&` reference". The new version with your suggested changes is at https://github.com/mvolkmann/rust-tide-demo/blob/master/src/main.rs#L57.

**Comment by pepoviola** [comment]
Hi @mvolkmann, yes my snippet isn't correct. I didn't test it  but I think this will work

```
app.at("/dog")
        .post(|mut req: Request<State>| async move {
            let dog: Dog = req.body_json().await?;
            let mut dog_map = req.state().dog_map;
            dog_map.insert(dog.id, dog);
            let res = tide::Response::new(200);
            res.set_body(Body::from_json(&dog)?);
            Ok(res)
        });
```

You need to declare `mut` the request and remove the `&` from the line that you get the hashMap from the state.

Ping me if keep failing and I can try to run the repo.

Thx!

**Comment by jbr** [comment]
closing this issue since it seems resolved

**Comment by mvolkmann** [comment]
Your last suggestion still does not work. I get "cannot move out of a shared reference" for `req` in the line `let mut dog_map = req.state().dog_map;`. I wish I knew how to fix this, but I'm too new to Rust to figure it out. I'm trying to show side-by-side comparisons of the popular server frameworks for Rust and I'd really like Tide to have a good showing. Can you take another look at this and suggest a fix? I've updated by repo linked above with code from your latest suggestion.

**Comment by pepoviola** [comment]
Hi @mvolkmann, let me checkout your repo and create a pr there.
Thx!

**Comment by mvolkmann** [comment]
Do I need to use `parking_lot::RwLock` and `std::sync::Arc` like this example?
https://collectednotes.com/javier/let-s-create-a-basic-crud-with-rust-using-tide

**Comment by pepoviola** [comment]
Hi @mvolkmann, yes. You need to use a `mutex` ( Arc/RwLock ) to share and update the HashMap. I just send you a `pr` in your repo.  Also, if you are interested the complete serie of that link is posted here https://javierviola.com/tags/tide-basic-crud/

Thx!

**Comment by mvolkmann** [comment]
Sorry to say this is still not working for me. I added comments about testing this will curl commands. I also added some `println!` calls so I can tell how far it is getting. It seems that the POST service is not able to parse the JSON in the request body. See https://github.com/mvolkmann/rust-tide-demo/blob/master/src/main.rs#L60

**Comment by pepoviola** [comment]
Hi @mvolkmann, You are getting `HTTP/1.1 422 Unprocessable Entity` since you are not sending the `id` and is not *Optional* in the `dog struct`.

Sending the `id` will work

```
curl -X POST -d'{"id":"aad396bf-6469-4a88-b11b-ac7586d2df6e","breed":"Whippet","name":"Comet1"}' localhost:8080/dog
{"id":"aad396bf-6469-4a88-b11b-ac7586d2df6e","breed":"Whippet","name":"Comet1"}
```

If you want we can continue with the example in your repo.
Thx!
