### ISSUE TITLE
tokio supported?

### ISSUE THREAD

**Issue by mvolkmann** [http-rs/tide#791]
I see that all of the examples use async_std rather than tokio.
I don't have a particular reason to want to use tokio with tide, but I'd like to know if it is possible.
If it is possible, are you aware of an example outside of this repo that does that?

**Comment by jbr** [comment]
I looked into writing a tokio Listener for tide at some point, but ran into issues. I think it might still be possible to run tide on tokio, but haven't seen anyone do it yet, and it's certainly not straightforward. This has to do with async-h1's clone bound for the io stream, which tokio::net::TcpStream did not have at the time (this was before tokio 1)

**Comment by jbr** [comment]
Potentially you could use async-std's network library on top of tokio's runtime using async-compat, but it's unclear to me what the benefits of that hybrid approach would be. The only part of tokio that this approach would use would be spawning a new async-compat future onto the tokio runtime
