### ISSUE TITLE
Deploying Tide application

### ISSUE THREAD

**Issue by evoxmusic** [http-rs/tide#792]
Hi 👋, do you have official documentation to explain to users how to deploy their Tide app? I can do it for you. Let me know. Thanks. Romaric

**Comment by Fishrock123** [comment]
I don't think we do, but it is the same for any Rust application. There is a binary called the same as your project name in either `target/debug/` or `target/release/`. Prefer `--release` builds for real deploys.

**Comment by mendelt** [comment]
Thank you for the feedback. I was actually planning to write a chapter about this in the tide-book that's currently being worked on; https://http-rs.github.io/tide-book/ but it might take a couple of weeks before I get to this.
In the meantime there is this article; https://gruberbastian.com/posts/deploy_rust/

A subject like this will of course be quite generic, as details will be different depending on the platform you use etc. So if you have any suggestions on what you'd like to see let me know.

**Comment by mendelt** [comment]
I opened an issue in the tide-book repository [here](https://github.com/http-rs/tide-book/issues/10) to track this. @evoxmusic let me know if you have any input or even want to help write that chapter.
