### ISSUE TITLE
async-std  Upgrade to 1.9， so it  can choose the Tokio runtime feature

### ISSUE THREAD

**Issue by zhuxiujia** [http-rs/tide#793]
async-std  Upgrade to 1.9， You can select the Tokio runtime

**Comment by yoshuawuyts** [comment]
You can update to the latest version of `async-std` on your project by running:

```sh
$ cargo update
```

**Comment by Fishrock123** [comment]
I can confirm that this upgrade is possible without issues, as I am presently using it.
