### ISSUE TITLE
cant use Tide 0.13.0 build

### ISSUE THREAD

**Issue by CfirTsabari** [http-rs/tide#800]
WORKAROUND:
add this to your Cargo.toml:
```
log = { version = "0.4.14", features = ["kv_unstable_std"]}
```

this might be a bug in cargo, or the crates repository.
when trying to use tide 0.13.0 this is what I got:
```cargo
error[E0277]: the trait bound `std::string::String: log::kv::value::ToValue` is not satisfied
  --> /Users/cfirt/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.13.0/src/listener/failover_listener.rs:90:21
   |
90 | /                     crate::log::info!("unable to listen", {
91 | |                         listener: listener.to_string(),
92 | |                         error: e.to_string()
93 | |                     });
   | |_______________________^ the trait `log::kv::value::ToValue` is not implemented for `std::string::String`
   |
   = note: required for the cast to the object type `dyn log::kv::value::ToValue`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

after checking it I saw that the `Cargo.lock`  in the registry and in the  [build log ](https://docs.rs/crate/tide/0.13.0/builds/276890), i figured it's because the build is using `kv-log-macro` version `1.0.7`.

this issue is related to #787.

is there a way to mark the build as broken? or fix it if it's better?

**Comment by jbr** [comment]
Hypothetically we could issue a 0.13.1 patch or yank 0.13, but I'm not sure how worthwhile that is. Is there a strong reason you need to stay on 0.13 instead of upgrading?

**Comment by CfirTsabari** [comment]
hi,
it's somehow broke an old release of ours.
but it's not critical to fix it since there is a workaround.
I guess this issue will help others find this workaround in case of a problem
