### ISSUE TITLE
Consider using SameSite=Lax as default for SessionMiddleware

### ISSUE THREAD

**Issue by jlkiri** [http-rs/tide#801]
I don't want to make it very personal but I wasted about 5 hours on a bug that was due to SameSite=Strict that is tide's default. Browsers treat SameSite as Lax if it's not specified, and I think that many developers expect the cookie behavior to be Lax intuitively. For example, when after successful payment on a different domain I'm redirected to my own site I want to send a cookie with my access_token but I can't because of Strict. I'm aware it is in the docs but I somehow managed to not notice it, because I didn't expect the bug to be caused by it.

**Comment by pepoviola** [comment]
Hi @jlkiri, thanks for reporting. Ping @yoshuawuyts this is also true for using OAuth2 with tide, you need to set the `same_site_policy` explicit to `Lax` like this:

```rust
app.with(tide::sessions::SessionMiddleware::new(
        tide::sessions::MemoryStore::new(),
        std::env::var("TIDE_SECRET")
            .expect("Please provide a TIDE_SECRET value of at least 32 bytes")
            .as_bytes(),
        ).with_same_site_policy(SameSite::Lax)
    );
    ```
    
Thanks!

**Comment by jbr** [comment]
I can't remember why I picked Strict, but a bit of research makes it seem like Lax is in fact correct. The default should change
