### ISSUE TITLE
Body::chain method to chain two Body instances together

### ISSUE THREAD

**Issue by joshtriplett** [http-rs/tide#804]
Sometimes, you have two or more things that can be turned into a `Body` (for instance, a `String` and a `Read` instance), and you want to chain them together. I'd love to have a direct method to chain these together (which could delegate to [Read::chain](https://docs.rs/async-std/1.9.0/async_std/io/trait.Read.html#method.chain)).

**Comment by jbr** [comment]
Would `Body::from_string(&my_string).chain(Body::from_reader(&stdin, None))` really be preferable to `Body::from_reader(Cursor::new(&my_string).chain(stdin), None)`?

**Comment by joshtriplett** [comment]
Yes, not least of which because it's possible to get the lengths right if known.

https://github.com/http-rs/http-types/pull/342

**Comment by joshtriplett** [comment]
This is now merged in http-types. It'll be available in tide when tide migrates to the new version of http-types.
