### ISSUE TITLE
Taking extension values out of Request

### ISSUE THREAD

**Issue by fominok** [http-rs/tide#819]
Hello,
I work with Tide and async-graphql-tide which provides a convenient method to convert from Tide's Request into GraphQL request, however, it takes whole Request by value denying all its extension values; currently I need to clone extension value first in order not to loose it before putting it into GraphQL request context.
A simple solution might be to take `ext` from Request by value, but I see no such method, is it doable and worth it to implement in Tide?

**Comment by jbr** [comment]
I've also run into this. Here's a workaround that drops down to a http_types request:
```rust
let inner_req: &mut tide::http::Request = r.as_mut();
let removed_ext = inner.ext_mut().remove::<SomeType>();
```

I'm not entirely sure why `ext_mut()` returns `Option<T>` instead of &mut Extensions, or why remove isn't called take, but I'm also not sure what the path forward is

**Comment by fominok** [comment]
Thank you @jbr, I missed the `remove` function
