### ISSUE TITLE
implement from/into for tide::Request<State> and &http_types::Request

### ISSUE THREAD

**Issue by prabirshrestha** [http-rs/tide#830]
I'm trying to create a generic webdav handler for `http_types::Request` and `https::types::Response` so it can work with any server.

```rust
use http_types::{Request, Response};

async fn handle_webdav_request(request: &Request, vfs: Vfs) -> Result<Response> {
    todo!();
}
```

Then in tide I can use it as follows.

```rust
app.at("/webdav")
    .all(|req: tide::Request<State>| async move {
        Ok(handle_webdav_request(http_request.into(), OsFs::new("./path")).await?)
    });
```

Would it be possible to get the inner reference for [tide::Request::req](https://github.com/http-rs/tide/blob/d441ae06ac8ba8c7e9b8514301baf3c7834381bc/src/request.rs#L29) which is currently set as `pub(crate)`.

The other option would be to expose api to convert `tide::Request<T>` to `http_types::Request`.

**Comment by jbr** [comment]
You could use Into for that

**Comment by Fishrock123** [comment]
You're looking for `AsRef<http_types::Request>` which is [already implemented](https://docs.rs/tide/0.16.0/tide/struct.Request.html#impl-AsMut%3CRequest%3E).

`From` and `Into ` _consume_ their `self`, which is almost never what you'd want here. `AsRef` and `AsMut` should do what you need.
