### ISSUE TITLE
Why do I need a State struct for a middleware?

### ISSUE THREAD

**Issue by amitavaghosh1** [http-rs/tide#843]
This is more of an enhancement request.

First of all, the middleware definition is a bit complex. (Comparing to something like routerify). But having said that, when I want to implement a middleware, which performs simple tasks like validating headers, modifying headers. I don't see the point of creating an extra struct.
Can this not be simplified to 
- either pass a function with a specific signature, like go or nodejs
- the existing one impl<State: Clone + Send + Sync + 'static> Middleware<State> where one actually need state. but more like `impl Middleware<State> for Struct` defaulting to Clone Send Sync using macros probably.

**Comment by jbr** [comment]
I think there is likely some misunderstanding here, but it's unclear how to help without some code samples to talk about. Why do you need to create an extra struct to define a middleware? Are you writing an application or a library?

**Comment by amitavaghosh1** [comment]
I am writing a web application, which exposes apis. So I needed a middleware to remove some headers based on certain parameters.
So I went through the example here https://github.com/http-rs/tide/blob/main/examples/middleware.rs . Both the examples are clear to me, in both of them there is form of "state" that is being used. In the first one, its a `UserDatabase` struct and in the second one, its a `RequestCounterMiddleware`. 
And I went through the docs here: https://docs.rs/tide/0.16.0/tide/trait.Middleware.html . 

In all the examples, there is a Request<State> that is required. That is the thing I am referring to. Based on my requirement I do not need that extra `State` struct there. which feels a bit odd.

**Comment by Fishrock123** [comment]
https://github.com/Fishrock123/tide-compress is a good example for how to write a full self-contained Tide middleware library, which may be helpful.

Standalone middleware does not know what the type of the state for any possible application is, so we use [generics](https://doc.rust-lang.org/book/ch10-01-syntax.html) (which do not exist in Go or JavaScript, but do exist in C#/TypeScript/Java/etc) to let the compiler know that state can be "anything which looks like these traits".

**Comment by jbr** [comment]
If you're writing an _application_ vs a library, and don't need a state struct, you can use tide::new and use `()` as the state instead of using a generic. Does that help? `Request<()>`, `Next<'a, ()>`, and `impl Middleware<()> for MyMiddleware`

**Comment by amitavaghosh1** [comment]
can you please provide an example. that would be very helpful. or even pseudo code.

**Comment by amitavaghosh1** [comment]
Ok, that makes sense. I will try it out. I am closing the issue for now then. If it doesn't work I will repoen.

**Comment by amitavaghosh1** [comment]
Hi.
Sorry for reopen-ing this. I had one more question, and I am stuck with the implementation.

So I have a controller as such:

```
struct UsersController {
  isAdmin: bool,
  repo: repositories::UserRepo
}

impl UsersController {
  pub fn new(repo: repositories::UserRepo, isAdmin: bool) -> Self {
    UsersController{isAdmin, repo}
  }

  pub async fn get(&self, req: tide::Request) -> tide::Result {
    todo!("implementation: read from query params and call self.fetch(find_user_struct)");
  }

  pub async fn create(mut req: tide::Request) -> tide::Result {
    todo!("implementation")
  }
}
```

and then in my main.rs

```
#[tokio::main]
async fn main() {
  let mut app = tide::new();
  let admin_ctrl = Arc::new(controllers::UsersController::new(r, true));  
  let users_crtl = Arc::new(controllers::UsersController::new(r, false));
 
  app.at("/internal/users").nest({
        let mut router = tide::new();
 
        router.at("").post(|req: tide::Request| async move { admin_ctrl.clone().create(req).await? } //this doesn't work
    });

   app.at("/users").nest({
       let mut router = tide::new();

      // router.at("").get(...)
   })
}
```

But in no way can I get this to work. Either it complains, that it needs a static thinggy, or the closures are FnOnce whereas it needs Fn . 

What is the general workaround for this?

**Comment by jbr** [comment]
Ok, there are a number of issues here:

1. you'll want to use async-std instead of tokio. even if you run it inside of a `#[tokio::main]`. You will certainly want to use `#[async_std::main]` if you continue with tide.
2. Tide doesn't have a notion of controllers, and I recommend getting comfortable with tide's patterns before inventing new ones. You'll want to move all of the state like UserRep into a State struct, and use `tide::with_state(State::new())`.  The closest there is to a controller is a nested application, which might serve your purpose. Create a new factory function that returns a tide::Server, like `users_app(repo: UserRepo, is_admin: bool) -> tide::Server<UserAppState>` and then mount that using `Server::nest`. When you do `admin_ctrl.clone()` inside of the post handler, it still moves into that scope. The best way to have a clone per request in tide is to put it in app state.

I'm not sure if it would be helpful, but you might like looking at https://github.com/jbr/tide-example for ideas. I believe there are several other example apps listed in the readme as well

**Comment by jbr** [comment]
It's important to frame this in terms of learning tide's patterns, not reusing patterns from other frameworks and expecting them to work. Every rust web framework has a different approach, and patterns often can't be directly translated.
