### ISSUE TITLE
Cookie_string parsed incorrectly when reading an incoming cookie.

### ISSUE THREAD

**Issue by PSPanesar** [http-rs/tide#862]
Hi Everyone. 

I am building a web server with tide and I've run into a little bit of an issue when parsing the cookie from the header in that the string seems to only be partially parsed. I've copied the cookie information below. I wonder, am I doing something incorrect? the value of the cookie does not seem to match the token in the cookie_string. Would really welcome any advice anyone could give me on this issue.

Thanks,

```rust
Cookie {
    cookie_string: Some(
        "bearer=`vbxsvXIODh8uroxHtx+9ofj%2Ftj5qcI4shqP9Z3KcjcLt0HM5eLCfa2zpJSZhGahp6GjtPtjfQt6z5fJvZdv%2F0A
%3D%3D`",
    ),
    name: Concrete(
        "bearer",
    ),
    value: Concrete(
        "`vbxsvXIODh8uroxHtx+9ofj/tj5qcI4shqP9Z3KcjcLt0HM5eLCfa2zpJSZhGahp6GjtPtjfQt6z5fJvZdv/0A==`",
    ),
    expires: None,
    max_age: None,
    domain: None,
    path: None,
    secure: None,
    http_only: None,
    same_site: None,
}
```

**Comment by jbr** [comment]
The cookie string is url (percent) encoded. The value field is decoded

**Comment by PSPanesar** [comment]
Hi jar, thanks for your reply. I’ve attached the bearer token to the header when making a REST call. When comparing the token to the cookie value in the back end for auth it fails. Should i be doing some kind of encoding to the token before attaching it? I wonder if you could advise me on the proper flow? I’m self taught for coding so forgive me if this is super obvious but i am a bit stuck with it. Thanks

**Comment by jbr** [comment]
I think I'd need more info to be able to help. Are you sure you want to be rolling your own auth. system? Do you control both the client and the server? Can you possibly use sessions and put a user id or similar into a session? If it has to be a bearer token, where are you getting the other one that doesn't match the urldecoded one in the cookie value?

**Comment by PSPanesar** [comment]
HI, thanks for your reply. I think I'll need to research things in more detail. Im sure I'm missing something. I may need to try sessions instead or look for an Auth library for tide.
