### ISSUE TITLE
How to do RBAC authorization when using tide?

### ISSUE THREAD

**Issue by zwl1619** [http-rs/tide#873]
How to do RBAC authorization when using tide?

**Comment by mdtusz** [comment]
This isn't really something that should be handled by tide directly as it's a fairly lightweight and unopinionated server framework/library.

RBAC can be implemented in _many_ ways, and is largely schema dependent, but tools like [casbin](https://github.com/casbin/casbin-rs) can be used - implementation and integration is up to you, however.
